(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [
		{name:"index_atlas_", frames: [[876,55,117,41],[730,0,144,90],[0,0,728,90],[876,0,127,53]]}
];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != null && cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != null && cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != null && cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib.nineteenbottomleft = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.nineteenbottomright = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.nineteentable = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.nineteentopright = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.topright = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.nineteentopright();
	this.instance.parent = this;
	this.instance.setTransform(-63.5,-26.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.topright, new cjs.Rectangle(-63.5,-26.5,127,53), null);


(lib.readytoserveshrimp = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("Ag7BTQgFgCAAgFQAAgEAEgCIAHgDQADgDAAgJQABgKAAgeIAAgTQAAghgBgKQgBgKgDgBIgGgCQgHgDAAgEQAAgDADgCIAGgEIASgFIAMgCQADAAACABQABACAAAFIAAAGIABACIABABIAEgEIAFgDQAIgGAFgCQAHgDAIAAQAWAAAPARQAOAQAAAbQAAAcgQATQgQATgaAAQgKAAgDgDQgEgDAAgFQAAgBAAAAQAAgBABgBQAAAAAAgBQABAAAAgBQACgCADAAIADABIAEAAQANAAAJgLQAIgLAAgSQAAgVgJgNQgJgNgNAAQgNAAgHAHQgHAHAAATIAABNIABAMQAAAFACABQABACAGACIAEABIADACIABAEQAAAEgHACQgHACgSAAQgRAAgHgCg");
	this.shape.setTransform(121.9,5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AA2A8QgGgBAAgFQAAgEAHgDIAEgCQADgCACgFIABgVQAAgkgGgJQgFgKgNAAQgNAAgHANQgGAMAAAcIAAAHQAAAOACAEQABAEADACIADABQAGACAAAEQAAAGgFABQgGACgTAAQgQAAgGgCQgGgBABgFQAAgEAFgDIAFgCQADgBABgFIABgTQAAgmgFgKQgFgKgNAAQgHAAgFAEQgGAEgDAHQgDAFgBAKIgBAgQAAAMABAEQABADACACIAFACQAHADAAAEQgBAFgGACQgFABgRAAQgSAAgGgCQgHgBAAgGQAAgEAHgCIADgBQADgCACgEIABgOIAAgHIAAgLIAAgGQAAgXgBgGQgBgHgDgCIgGgCQgHgCAAgEQAAgBAAAAQAAgBAAAAQABgBAAAAQABgBAAgBIAIgEIASgGIAMgCQABAAAAAAQABAAABAAQAAAAABABQAAAAABABQABACABAEIAAAGIAAACIAAABIAAABIABAAIAAgBIAEgDIABgBQAOgNAQAAQAFAAAFACQAGABAEADQAEAEAFAFIAFAGQACAAAEgFIAEgFQAIgGAHgDQAGgCAGAAQAOAAAMAFQAKAGAFAKQAFAMAAAiIAAANIAAAGIAAAGQAAAHABADQACADADACIACABQAHACAAAEQAAAGgGABQgGACgTAAQgRAAgGgCg");
	this.shape_1.setTransform(103.8,2.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AgVBXQgGgCAAgFQAAgFAGgCIADgBQADgCACgEIABgNIAAgIIAAgKIAAgMQAAgUgBgFQgBgFgDgCIgFgCQgIgDAAgEQAAgCACgDIAIgEIASgGIAMgCQAEAAABACQACADAAAFIAAAHIgBAGIgBAeIAAABIAAAeQAAAMABAEQABAGADAAIAEACQAHADAAAEQAAAFgGADQgGABgQAAQgSAAgGgCgAgOg9QgGgEAAgHQAAgGAGgFQAGgFAIAAQAHAAAFAFQAGAEAAAHQAAAGgGAFQgGAFgHAAQgIAAgFgFg");
	this.shape_2.setTransform(89.2,0.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AgkA8QgGgBAAgGQAAgEAGgCIADgBQADgCABgEQACgEAAgKIgBgHIAAgLIAAgGQAAgXgBgGQAAgHgDgCIgGgCQgHgCAAgEQAAgDADgCQACgCAFgCIAQgFIAMgCQAFAAACAQIAAADIABAAQAGgKAHgFQAGgGAIABQAIgBAFAGQAFAFAAAJQAAAIgEAFQgEAFgHAAIgGgBIgFgEIgDgFQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAAAgBAAQgIAAgDAMQgDALAAAkQAAALABAGQABAFADABIAGACQAHACAAAFQAAAEgHACQgHACgQAAQgSAAgGgCg");
	this.shape_3.setTransform(81.5,2.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AARBYQgGgCAAgFQAAgEAGgDIAFgCQACgCACgEIABgSQAAgogFgJQgFgKgNAAQgGAAgGAEQgFAEgEAGQgCAFgBAJIgBAhQAAANABAEQABAEACABIAFACQAGADAAAEQAAAFgGACQgGABgQAAQgTAAgGgCQgGgBAAgGQAAgEAGgCIADgBQAEgCABgFIABgSIAAgUIAAgTIAAg3QgBgNgCgDQgBgCgIgCQgHgBAAgFQAAgDADgCIAOgHIAMgDIAMgBQAEAAABACQACACAAAGIAAAFIgBAxIAAAFIAAAEIACABIADgEIAEgEQAGgHAHgCQAGgDAIAAQAVAAAKANQAKAOAAAbIAAALIAAAVIAAAHQAAAHACACQABADADACIADABQAGACAAAEQAAAGgGABQgGACgTAAQgQAAgGgBg");
	this.shape_4.setTransform(69.1,0);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AgdBYQgOgDgIgFQgFgDgDgKQgEgLAAgNQAAgGADgDQACgDAEAAQAFAAAGALIADAFQAIAOAJAGQAJAGANAAQANAAAJgIQAJgIAAgLQAAgSgjgPIgEgCQgegMgKgKQgJgMAAgQQAAgWAQgOQAQgPAaAAIAOABIAQAEIAFgDIAEgBQADAAADACQACACADAEIAGAQQADAHAAAHQAAAEgCACQgCACgEAAQgGAAgGgJIgCgCQgHgJgIgEQgIgEgKgBQgNABgIAGQgIAHAAALQAAAKAHAGQAGAHAaALIAFACQAVAJAKAIQAHAGADAIQAEAJAAAJQAAAZgRAOQgSAOgeAAQgPAAgNgDg");
	this.shape_5.setTransform(54.9,0.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AgnAuQgRgSAAgaQgBgcATgSQASgTAbAAQAXAAAOAOQANANAAAXQAAAIgCACQgCACgJAAIguAAQgEAAgDgCQgBgCAAgDQAAgDABgCQACgCAFAAIAZAAIAFgBQABAAAAAAQAAAAABgBQAAAAAAgBQAAAAAAgBQAAgMgIgIQgIgIgLAAQgOAAgHANQgHAMAAASQAAASAKAOQAJAOAPAAQAJAAAHgCQAGgCAFgEIAFgDQAGgFAEAAQAAAAABAAQAAAAABAAQAAAAABABQABAAAAAAQAAABABAAQAAABAAAAQAAABAAABQAAAAAAABQAAADgDAEQgDAEgFAEQgKAJgKAEQgKAEgMAAQgYAAgSgSg");
	this.shape_6.setTransform(34.7,2.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AgMAzQgHgLgRgoIgHgSQgJgXgFgDIgEgCQgHgCAAgFQAAgFAGgCQAGgCAUAAQAQAAAGACQAGACAAAFIAAAEIgDACIgEACQgFACAAACIADAKIAJAYIAKAXQADAFABAAQABAAAAAAQAAAAABgBQAAAAABgBQAAAAABgBIAFgLIAOgeQAEgLAAgFIgBgEIgDgDIgDgCQgGgCAAgDQAAgFAGgCQAFgCAPAAQANAAAFACQAFACAAAFQAAAEgGADIgEABQgGADgKAYIgDAIIgFAKQgcA/gHAAQgFAAgHgMg");
	this.shape_7.setTransform(22,3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AgkA8QgGgBAAgGQAAgEAGgCIADgBQADgCABgEQACgEAAgKIgBgHIAAgLIAAgGQAAgXgBgGQAAgHgDgCIgGgCQgHgCAAgEQAAgDADgCQACgCAFgCIAQgFIAMgCQAFAAACAQIAAADIABAAQAGgKAHgFQAGgGAIABQAIgBAFAGQAFAFAAAJQAAAIgEAFQgEAFgHAAIgGgBIgFgEIgDgFQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAAAgBAAQgIAAgDAMQgDALAAAkQAAALABAGQABAFADABIAGACQAHACAAAFQAAAEgHACQgHACgQAAQgSAAgGgCg");
	this.shape_8.setTransform(11.3,2.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AgnAuQgSgSAAgaQABgcARgSQASgTAbAAQAYAAANAOQAOANABAXQgBAIgCACQgCACgJAAIguAAQgFAAgCgCQgCgCAAgDQAAgDACgCQACgCAEAAIAaAAIAGgBQAAAAAAAAQAAAAABgBQAAAAAAgBQAAAAAAgBQAAgMgIgIQgHgIgLAAQgPAAgHANQgHAMAAASQAAASAKAOQAKAOAOAAQAJAAAGgCQAHgCAFgEIAFgDQAGgFADAAQABAAABAAQAAAAABAAQAAAAABABQABAAAAAAQAAABABAAQAAABAAAAQAAABAAABQABAAAAABQAAADgEAEQgCAEgGAEQgKAJgKAEQgKAEgLAAQgZAAgSgSg");
	this.shape_9.setTransform(-0.1,2.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("AgdBYQgOgDgIgFQgFgDgDgKQgEgLAAgNQAAgGADgDQACgDAEAAQAFAAAGALIADAFQAIAOAJAGQAJAGANAAQANAAAJgIQAJgIAAgLQAAgSgjgPIgEgCQgegMgKgKQgJgMAAgQQAAgWAQgOQAQgPAaAAIAOABIAQAEIAFgDIAEgBQADAAADACQACACADAEIAGAQQADAHAAAHQAAAEgCACQgCACgEAAQgGAAgGgJIgCgCQgHgJgIgEQgIgEgKgBQgNABgIAGQgIAHAAALQAAAKAHAGQAGAHAaALIAFACQAVAJAKAIQAHAGADAIQAEAJAAAJQAAAZgRAOQgSAOgeAAQgPAAgNgDg");
	this.shape_10.setTransform(-13.7,0.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AgXANQgEAAgCgCQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAgBAAAAIABgGIADgGQABgEACgBQACgBAFAAIAGAAIAKAAIAVAAIADgBQAEAAACACQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAABQAAAHgDAFQgEAGgGAAIgGAAIgHAAIgaABIgCAAg");
	this.shape_11.setTransform(-24.8,2.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AgsAuQgRgSAAgcQAAgaASgSQATgTAaAAQAbAAAQARQARASAAAaQAAAcgSATQgSATgaAAQgaAAgSgSgAgWgkQgIAKAAARQAAAXALAQQAKARAOAAQAMAAAHgLQAIgKAAgQQAAgXgLgQQgLgRgNAAQgMAAgHAKg");
	this.shape_12.setTransform(-35.8,2.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("AgFBKQgHgCgEgFQgEgEgCgGQgCgHAAgTIAAhAIgLAAIgEgBIgBgDIAAgDQAAgEANgKIAFgFIAFgEQANgMAEAAIADACQABAAAAABQAAAAAAAAQABAAAAABQAAAAAAABIAAAWIAbAAIAEACIABAEIAAADQAAADgBACIgEABIgZAAIgCABIgBADIAAA8QAAAQADADQACAFAHAAQAEAAAGgCIAJgDQAAAAABABQABAAAAAAQABAAAAAAQABABAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAAHgKAGQgLAGgNAAQgHAAgFgBg");
	this.shape_13.setTransform(-47,1.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("AgXANQgEAAgCgCQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAgBAAAAIABgGIADgGQABgEACgBQACgBAFAAIAGAAIAKAAIAVAAIADgBQAEAAACACQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAABQAAAHgDAFQgEAGgGAAIgGAAIgHAAIgaABIgCAAg");
	this.shape_14.setTransform(-55.5,2.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("Ag3BRQgHgFAAgIQABgGAEgFQAEgEAGAAIAFABIAFADIACAEQAEAFACAAQAHAAAGgJQAGgJAAgKQAAgKgIgTIgBgDIgUgqIgMgYQgBgEgIgDIAAAAIgFgEQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgFAGgDQAHgCASAAQARAAAHACQAFACAAAFIAAAEIgCACIgFACQgEACAAACIACAJIAJAZIAKAXQADAGACAAQABAAADgGIAIgTIAJgZIADgLQAAgEgHgEQgHgEAAgDQAAgEAGgCQAFgCAOAAQAPAAAEACQAGACAAAFQAAAFgHABIgFACQgHAEgIAVIgEAJIgPAmQgUAzgMAPQgNAQgSAAQgJAAgFgFg");
	this.shape_15.setTransform(-65.6,5.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E47").s().p("AAYBYQgBgCgBgEIAAgGIAAgCIgBgBIgDADIgGAEQgHAFgGADQgHACgHAAQgXAAgOgQQgPgQAAgbQAAgeARgRQAQgTAaAAIAJABQADABACADQACACAAAEQAAAGgIAAIgDAAIgDAAQgOAAgIALQgHAKAAATQAAAVAJAMQAIANAOAAQAMAAAHgHQAHgHAAgNIAAgiIAAg3QAAgJgBgDQgCgDgFgCIgDgBQgHgCgBgEQABgEACgCIANgGIANgEIALgBQAFAAABACQACADAAAFIAAAGIgCBLIABAzQABALADACIAIADQAGABAAAFQAAAFgSAGIgLADIgKABQgDAAgCgCg");
	this.shape_16.setTransform(-78.6,0.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E47").s().p("AAWA6IgHgHIgFADQgOAKgPAAQgSAAgLgKQgLgLAAgRQAAgTAOgKQAOgLAZAAQAGAAADACQADACAAAEQAAAGgIAAQgMAAgHAGQgHAGAAALQAAAJAGAGQAGAGALAAQALAAAFgFQAFgGAAgMIAAguQAAgLgEgFQgFgGgIAAQgGAAgFACQgFADgFAGIgCADQgIAJgIAAQgFAAgDgDQgDgDAAgFQAAgMAPgIQAOgIAWAAQANAAAJAEQAKAEAFAGQAEAFACAIQABAHAAARIAAAnIABAKQABAEADAAIAEABQAHACAAAFQAAAFgIAFQgIAFgLAAQgFAAgGgGg");
	this.shape_17.setTransform(-92.7,2.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#006E47").s().p("AgnAuQgSgSAAgaQABgcARgSQASgTAbAAQAYAAANAOQAOANABAXQgBAIgCACQgCACgJAAIguAAQgEAAgDgCQgCgCAAgDQAAgDACgCQADgCADAAIAZAAIAHgBQAAAAAAAAQAAAAABgBQAAAAAAgBQAAAAAAgBQAAgMgIgIQgHgIgLAAQgPAAgHANQgHAMAAASQAAASAKAOQAKAOAOAAQAJAAAGgCQAHgCAGgEIAEgDQAGgFADAAQABAAABAAQAAAAABAAQAAAAABABQAAAAABAAQAAABABAAQAAABAAAAQAAABAAABQABAAAAABQAAADgEAEQgDAEgEAEQgLAJgKAEQgKAEgLAAQgaAAgRgSg");
	this.shape_18.setTransform(-105.7,2.8);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#006E47").s().p("AAaA9QgLgngJgIQgIgIgMAAQgKAAAAgHQAAgHAIAAQAUAAAKgIQAJgIAAgRQAAgQgKgIQgJgIgTAAQgJAAgEABQgDABgBAEIgCAKIAAAZIAAA1IABAlQAAAIADACIAFADQAHACAAAFQAAAGgGACQgHACgTAAQgTAAgHgCQgHgCAAgGQAAgFAIgDIAFgCQADgCABgPIABg0IgBguQgBgSgCgCQgBgCgHgCQgGgDAAgFQAAgEAEgCQADgCAIAAIAbAAIAYgBIATAAQAbAAAOALQAOALAAAWQAAAQgJAMQgKAMgRAEIAAABQANADAIAIQAHAIAGAUIADAMQAFATAHAAIAEgBIAEAAQABAAAAAAQABAAAAABQABAAAAAAQABABAAAAQABABAAAAQAAAAABABQAAAAAAABQAAABAAAAQAAAGgHAEQgHADgLAAQgYAAgJgcg");
	this.shape_19.setTransform(-120.6,0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.readytoserveshrimp, new cjs.Rectangle(-131.6,-16.5,263.3,33), null);


(lib.partyperft = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AgJA/IgMgCIgEACIgEABIgCAAIgDgCQgEgDgDgKQgEgKAAgJQAAgEADgDQACgCACAAQAGAAAGAKIAFAHQADAFAGADQAHACAGAAQAIAAAFgEQAFgEgBgHQAAgKgTgKIgHgDQgTgKgHgHQgGgIAAgLQgBgQAMgKQALgKARAAIAIAAIAIACIAHgCIADgBQAGAAAGAKQAFAJAAALQAAAEgBADQgCACgEAAQgDAAgCgCQgDgDgEgGQgEgHgFgDQgFgDgGAAQgHAAgEAEQgEAEAAAGQAAAGAEAEQAEAEAPAIIABABQAiAQAAATQAAARgNAMQgNALgUAAg");
	this.shape.setTransform(148.9,2.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AgUBXQgGgBAAgGQAAgEAFgBIAHgEQACgCABgIIAAgXIAAgTIAAgXIAAgJQAAgfgBgJQgBgJgDgBIgHgDQgIgCAAgEQAAgDADgCQACgDAJgDIAQgEIAMgBQADAAACACQABACAAAGIAAAJQgBArAAAsIABApQAAAKACABIAHAEQAGADAAAEQAAAFgGACQgGABgQAAQgSAAgGgCg");
	this.shape_1.setTransform(140.1,0);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AAHANIgOglQgHgRgGgDIgDgCQgHgCAAgFQAAgFAGgCQAGgCATAAQAQAAAGACQAHACAAAFIgBADIgDADIgEACQgFACAAACIADAIIAKAaIAKAXQADAFABAAQACAAACgDIAGgLIAMgeQAFgLAAgFIgBgEIgDgDIgDgCQgFgCgBgDQABgFAFgCQAFgCAPAAQANAAAGACQAEACABAFQAAAEgHADIgEABQgGADgLAaIgDAGIgEAKQgcA/gIAAQgJAAgVgygAhHAHIgEgHIgIgVQgHgUgFgDIgFgCQgGgCAAgFQAAgFAFgCQAHgCATAAQARAAAGACQAGACAAAFIgBAEIgCACIgEACQgFACAAACIADAKIAJAYIAKAWQADAGACAAQAEAAADgIIAEgIIADgEQAAAAAAAAQABAAAAgBQABAAABAAQAAAAABAAQABAAAAAAQABAAABAAQAAABABAAQAAABABAAQAAAAAAABQABAAAAABQAAAAAAABQABABAAABQgBADgDAHQgMAcgHAJQgFAJgFAAQgIAAgYg4g");
	this.shape_2.setTransform(127,3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AgsAuQgRgSAAgcQAAgaASgSQATgTAaAAQAbAAAQARQARASAAAaQAAAcgSATQgSATgaAAQgaAAgSgSgAgWgkQgIAKAAARQAAAXALAQQAKARAOAAQAMAAAHgLQAIgKAAgQQAAgXgLgQQgLgRgNAAQgMAAgHAKg");
	this.shape_3.setTransform(110,2.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AgIBYIgYgBIgMAAIgOABQgIAAgEgDQgFgCAAgEQAAgFAHgDIAIgEQABgDABgRIABgvIgBguQgBgSgBgCQgCgCgGgDQgHgCAAgFQAAgFAEgCQADgCAIAAIANAAIAOAAIAZAAIATgBQAaAAAOALQAOALAAAVQAAAQgKAKQgLALgTADQAZADANAKQANAMAAAUQAAAXgQANQgQANgeAAgAgShGQgEABgBACQgCADAAAMIgBAiIAAAzIABAYQAAAGACAEQACACAGACQAFABAKAAQAUAAALgIQAKgJAAgQQAAgRgMgIQgMgIgWAAQgKAAAAgHQAAgIAKAAQAQAAALgIQAKgHgBgQQAAgQgJgIQgKgHgTAAg");
	this.shape_4.setTransform(94.6,0.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AgnBJQgSgSAAgaQABgdARgRQASgTAbAAQAYAAANAOQAOANABAWQgBAIgCACQgCACgJAAIguAAQgFAAgCgCQgCgCAAgDQAAgDACgCQACgCAFAAIAZAAIAGgBQAAAAAAAAQAAAAABgBQAAAAAAgBQAAAAAAgBQAAgLgIgIQgHgIgLAAQgPAAgHANQgHALAAASQAAATAKAOQAKAOAOAAQAJAAAGgCQAHgCAFgEIAFgDQAGgFADAAQABAAABAAQAAAAABAAQAAAAABABQABAAAAAAQAAABABAAQAAABAAAAQAAABAAABQABAAAAABQAAADgEAEQgCAEgGAEQgKAJgKAEQgKAEgLAAQgZAAgSgSgAgNg0QgDgDgBgDIACgCIACgCIAogZIAEgCIADgBQADAAAEAFQAEAFgBAFQABADgIADIAAABIgrATIgCABIgBAAQgCAAgCgEg");
	this.shape_5.setTransform(73.3,0.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AgFBKQgHgCgEgFQgEgEgCgGQgCgHAAgTIAAhAIgLAAIgEgBIgBgDIAAgDQAAgEANgKIAFgFIAFgEQANgMAEAAIADACQABAAAAABQAAAAAAAAQABAAAAABQAAAAAAABIAAAWIAbAAIAEACIABAEIAAADQAAADgBACIgEABIgZAAIgCABIgBADIAAA8QAAAQADADQACAFAHAAQAEAAAGgCIAJgDQAAAAABABQABAAAAAAQABAAAAAAQABABAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAAHgKAGQgLAGgNAAQgHAAgFgBg");
	this.shape_6.setTransform(62.5,1.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AgVBXQgGgCAAgFQAAgFAGgCIADgBQADgCACgEIABgNIAAgIIAAgKIAAgMQAAgUgBgFQgBgFgDgCIgFgCQgIgDAAgEQAAgCACgDIAIgEIASgGIAMgCQAEAAABACQACADAAAFIAAAHIgBAGIgBAeIAAABIAAAeQAAAMABAEQABAGADAAIAEACQAHADAAAEQAAAFgGADQgGABgQAAQgSAAgGgCgAgOg9QgGgEAAgHQAAgGAGgFQAGgFAIAAQAHAAAFAFQAGAEAAAHQAAAGgGAFQgGAFgHAAQgIAAgFgFg");
	this.shape_7.setTransform(54.7,0.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AAYBYQgCgCABgEIAAgGIAAgCIgBgBIgEADIgFAEQgIAFgGADQgHACgHAAQgXAAgPgQQgOgQAAgbQAAgeARgRQAQgTAaAAIAIABQAEABACADQACACAAAEQAAAGgIAAIgDAAIgDAAQgNAAgJALQgHAKgBATQABAVAIAMQAJANAOAAQAMAAAHgHQAHgHAAgNIAAgiIAAg3QAAgJgBgDQgCgDgFgCIgDgBQgHgCAAgEQgBgEADgCIAMgGIAOgEIALgBQAFAAACACQABADAAAFIAAAGIgBBLIAAAzQABALACACIAJADQAGABAAAFQAAAFgSAGIgLADIgKABQgDAAgCgCg");
	this.shape_8.setTransform(44.5,0.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AAbA+QgCgCAAgEIAAgJIAAAAIgBAAIgEADIgBACQgHAGgHACQgGADgKAAQgIAAgIgDQgJgDgFgHQgGgHgCgKQgDgJABgaIAAgIIAAgJIAAgCQAAgKgBgDQgCgDgFgCIgEgBQgIgCABgEQgBgDADgCQACgCAJgDIAQgFIAOgCQADAAABADQACACAAAGIgBAFIgBAtQAAAYAGAKQAFAJAMAAQANAAAHgMQAFgNABgcIAAgKQAAgJgCgDQgBgDgEgCIgGgBQgGgCAAgEQAAgDACgCQACgCAJgDIARgFIAMgCQAEAAACADQABACAAAGIAAAGIgCAyIABAVIAAAIQABAFAHACIACABQAGACABAEQAAADgDACQgBACgGACIgRAGIgOACQgDAAgBgCg");
	this.shape_9.setTransform(29.5,2.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("AgkA8QgGgBAAgGQAAgEAGgCIADgBQAEgCABgEQABgEAAgKIAAgHIAAgLIAAgGQAAgXgBgGQgBgHgDgCIgFgCQgIgCAAgEQAAgDACgCQACgCAGgCIARgFIALgCQAFAAACAQIAAADIABAAQAGgKAHgFQAGgGAHABQAJgBAFAGQAFAFAAAJQAAAIgEAFQgDAFgIAAIgGgBIgFgEIgCgFQgBgBAAAAQgBgBAAAAQAAgBgBAAQAAAAAAAAQgJAAgDAMQgDALAAAkQAAALABAGQABAFAEABIAEACQAIACAAAFQAAAEgHACQgHACgPAAQgTAAgGgCg");
	this.shape_10.setTransform(18,2.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AgSBVQgRgGgMgLQgOgNgHgSQgIgSAAgVQAAgRAFgOQAFgPAKgMQAMgPARgHQARgIATAAIAPABIAYAFIADgBIAJgCIAEACIAEADQADAHADAJQACAJABAIQAAAFgCACQgDADgDAAQgGAAgJgLIgIgJQgGgHgKgDQgKgEgMAAQgXAAgNAQQgOARAAAcQAAAkARAXQASAXAaAAQAKAAAKgEQAJgDAHgGIAGgHQAFgHAEAAQADAAACADQACADAAAGQAAALgDAHQgEAHgFAAIgBgBIgCAAQgLAGgLADQgMADgNAAQgQAAgRgGg");
	this.shape_11.setTransform(4.8,0.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AgFBKQgHgCgEgFQgEgEgCgGQgCgHAAgTIAAhAIgLAAIgEgBIgBgDIAAgDQAAgEANgKIAFgFIAFgEQANgMAEAAIADACQABAAAAABQAAAAAAAAQABAAAAABQAAAAAAABIAAAWIAbAAIAEACIABAEIAAADQAAADgBACIgEABIgZAAIgCABIgBADIAAA8QAAAQADADQACAFAHAAQAEAAAGgCIAJgDQAAAAABABQABAAAAAAQABAAAAAAQABABAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAAHgKAGQgLAGgNAAQgHAAgFgBg");
	this.shape_12.setTransform(-14.8,1.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("AgmAuQgRgSAAgaQAAgbASgTQATgTAaAAQAUAAAOALQAOAKAAAOQAAAGgEAEQgEADgGAAQgGAAgEgDQgDgDgFgKQgDgIgFgEQgFgDgHAAQgOAAgHAKQgIALAAATQAAAUALAOQALAOARAAQAGAAAFgCIAKgFIAFgDQAHgFADAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQABABAAAAQAAABAAAAQABAAAAABQAAABAAAAQAAADgDAFIgGAHQgKAJgKAEQgLAEgMAAQgZAAgRgSg");
	this.shape_13.setTransform(-25.4,2.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("AgnAuQgRgSAAgaQgBgcATgSQARgTAcAAQAXAAANAOQAPANAAAXQAAAIgDACQgCACgJAAIguAAQgFAAgCgCQgBgCAAgDQAAgDABgCQACgCAFAAIAZAAIAFgBQABAAAAAAQAAAAABgBQAAAAAAgBQAAAAAAgBQAAgMgIgIQgIgIgKAAQgPAAgHANQgHAMAAASQAAASAKAOQAKAOAOAAQAJAAAHgCQAFgCAGgEIAFgDQAGgFAEAAQAAAAABAAQAAAAABAAQAAAAABABQABAAAAAAQAAABABAAQAAABAAAAQAAABAAABQAAAAAAABQAAADgDAEQgCAEgGAEQgKAJgKAEQgKAEgLAAQgZAAgSgSg");
	this.shape_14.setTransform(-38.1,2.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("AgiBXQgFgCgBgEQABgEAFgCIADgBQAEgCABgEQABgEAAgLIAAgMIAAg5IgOAAIgEgCIgBgEIAAgDQAAgBAAgBQAAAAAAgBQABAAAAgBQAAAAAAgBQABAAAAAAQAAAAABgBQAAAAABAAQABAAAAAAIANAAIgBgJIAAgJQAAgTALgKQALgLATABQAOgBAJAHQAIAGAAAKQAAAGgDACQgDADgGAAQgEAAgDgCQgDgBgCgDIgCgFQgFgJgHAAQgEAAgDADQgCAEgBAEIADAOQACALAAAIIASAAIAFABIABAFIAAADIgBAEIgFACIgRAAIAAA+QAAAPABAFQABAFACABIAFACQAHADAAAEQAAAFgGABQgGACgQAAQgTAAgGgCg");
	this.shape_15.setTransform(-46.9,0);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E47").s().p("AgkA8QgGgBAAgGQAAgEAGgCIADgBQADgCABgEQACgEAAgKIgBgHIAAgLIAAgGQAAgXgBgGQAAgHgDgCIgGgCQgHgCAAgEQAAgDADgCQACgCAFgCIAQgFIAMgCQAFAAACAQIAAADIABAAQAGgKAHgFQAGgGAIABQAIgBAFAGQAFAFAAAJQAAAIgEAFQgEAFgHAAIgGgBIgFgEIgDgFQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAAAgBAAQgIAAgDAMQgDALAAAkQAAALABAGQABAFADABIAGACQAHACAAAFQAAAEgHACQgHACgQAAQgSAAgGgCg");
	this.shape_16.setTransform(-55.8,2.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E47").s().p("AgnAuQgSgSAAgaQABgcARgSQASgTAbAAQAYAAANAOQAOANABAXQgBAIgCACQgCACgJAAIguAAQgFAAgCgCQgCgCAAgDQAAgDACgCQACgCAEAAIAaAAIAGgBQAAAAAAAAQAAAAABgBQAAAAAAgBQAAAAAAgBQAAgMgIgIQgHgIgLAAQgPAAgHANQgHAMAAASQAAASAKAOQAKAOAOAAQAJAAAGgCQAHgCAFgEIAFgDQAGgFADAAQABAAABAAQAAAAABAAQAAAAABABQABAAAAAAQAAABABAAQAAABAAAAQAAABAAABQABAAAAABQAAADgEAEQgCAEgGAEQgKAJgKAEQgKAEgLAAQgZAAgSgSg");
	this.shape_17.setTransform(-67.1,2.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#006E47").s().p("Ag+BWQgIgCAAgFQAAgFAIgDIAGgDQADgCAAgOIABg0IgBguQgBgSgBgCQgBgCgHgCQgGgDgBgFQAAgEAFgDQADgBAIAAIAMAAIAPAAIAYgBIATAAQAbAAAOALQAOALAAAYQgBAZgQAOQgRANghAAQgLgBAAgHQAAgJAKABQAPAAAJgJQAKgIAAgSQAAgQgKgJQgKgHgSgBQgJAAgEACQgDABgBADIgCALIAAAaIAAA1IABAjQAAAJACACIAGADQAHACAAAFQAAAFgGACQgHACgTAAQgUAAgGgCg");
	this.shape_18.setTransform(-80.6,0.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#006E47").s().p("AgXANQgEAAgCgCQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAgBAAAAIABgGIADgGQABgEACgBQACgBAFAAIAGAAIAKAAIAVAAIADgBQAEAAACACQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAABQAAAHgDAFQgEAGgGAAIgGAAIgHAAIgaABIgCAAg");
	this.shape_19.setTransform(-92.4,2.7);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#006E47").s().p("Ag3BRQgHgFAAgIQABgGAEgFQAEgEAGAAIAFABIAFADIACAEQAEAFACAAQAHAAAGgJQAGgJAAgKQAAgKgIgTIgBgDIgUgqIgMgYQgBgEgIgDIAAAAIgFgEQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgFAGgDQAHgCASAAQARAAAHACQAFACAAAFIAAAEIgCACIgFACQgEACAAACIACAJIAJAZIAKAXQADAGACAAQABAAADgGIAIgTIAJgZIADgLQAAgEgHgEQgHgEAAgDQAAgEAGgCQAFgCAOAAQAPAAAEACQAGACAAAFQAAAFgHABIgFACQgHAEgIAVIgEAJIgPAmQgUAzgMAPQgNAQgSAAQgJAAgFgFg");
	this.shape_20.setTransform(-102.5,5.3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#006E47").s().p("AgFBKQgHgCgEgFQgEgEgCgGQgCgHAAgTIAAhAIgLAAIgEgBIgBgDIAAgDQAAgEANgKIAFgFIAFgEQANgMAEAAIADACQABAAAAABQAAAAAAAAQABAAAAABQAAAAAAABIAAAWIAbAAIAEACIABAEIAAADQAAADgBACIgEABIgZAAIgCABIgBADIAAA8QAAAQADADQACAFAHAAQAEAAAGgCIAJgDQAAAAABABQABAAAAAAQABAAAAAAQABABAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAAHgKAGQgLAGgNAAQgHAAgFgBg");
	this.shape_21.setTransform(-113,1.7);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#006E47").s().p("AgkA8QgGgBAAgGQAAgEAGgCIADgBQAEgCAAgEQACgEAAgKIAAgHIAAgLIAAgGQAAgXgCgGQgBgHgCgCIgGgCQgHgCAAgEQAAgDADgCQACgCAFgCIARgFIALgCQAFAAACAQIAAADIABAAQAGgKAHgFQAGgGAIABQAIgBAFAGQAFAFAAAJQAAAIgEAFQgDAFgIAAIgGgBIgFgEIgCgFQgBgBAAAAQgBgBAAAAQAAgBgBAAQAAAAgBAAQgIAAgDAMQgDALAAAkQAAALABAGQABAFADABIAGACQAHACAAAFQAAAEgHACQgGACgRAAQgSAAgGgCg");
	this.shape_22.setTransform(-121.7,2.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#006E47").s().p("AAWA6IgHgHIgFADQgOAKgPAAQgSAAgLgKQgLgLAAgRQAAgTAOgKQAOgLAZAAQAGAAADACQADACAAAEQAAAGgIAAQgMAAgHAGQgHAGAAALQAAAJAGAGQAGAGALAAQALAAAFgFQAFgGAAgMIAAguQAAgLgEgFQgFgGgIAAQgGAAgFACQgFADgFAGIgCADQgIAJgIAAQgFAAgDgDQgDgDAAgFQAAgMAPgIQAOgIAWAAQANAAAJAEQAKAEAFAGQAEAFACAIQABAHAAARIAAAnIABAKQABAEADAAIAEABQAHACAAAFQAAAFgIAFQgIAFgLAAQgFAAgGgGg");
	this.shape_23.setTransform(-133.1,2.8);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#006E47").s().p("Ag+BWQgIgCAAgFQAAgFAIgDIAGgDQADgCAAgOIABg0IgBguQgBgSgBgCQgBgCgHgCQgGgDgBgFQAAgEAFgDQADgBAIAAIAMAAIAPAAIAYgBIATAAQAbAAAOALQAOALAAAYQgBAZgQAOQgRANghAAQgLgBAAgHQAAgJAKABQAPAAAJgJQAKgIAAgSQAAgQgKgJQgKgHgSgBQgJAAgEACQgDABgBADIgCALIAAAaIAAA1IABAjQAAAJACACIAGADQAHACAAAFQAAAFgGACQgHACgTAAQgUAAgGgCg");
	this.shape_24.setTransform(-146.7,0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.partyperft, new cjs.Rectangle(-156.4,-16.5,312.8,33), null);


(lib.nineteentable_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.nineteentable();
	this.instance.parent = this;
	this.instance.setTransform(-364,-45);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.nineteentable_1, new cjs.Rectangle(-364,-45,728,90), null);


(lib.nineteenright = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.nineteenbottomright();
	this.instance.parent = this;
	this.instance.setTransform(-72,-45);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.nineteenright, new cjs.Rectangle(-72,-45,144,90), null);


(lib.mainbutton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("EgQFAzRMAAAhmhMAgLAAAMAAABmhg");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.kalelogo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgeAfQgNgNAAgSQAAgRANgNQANgNARAAQASAAANANQANANAAARQAAASgNANQgNANgSAAQgRAAgNgNgAgYgYQgKAKAAAOQAAAQAKAKQAKAKAOAAQAPAAAKgKQAKgKAAgQQAAgOgKgKQgKgKgPAAQgOAAgKAKgAAMAZIgOgVIgFAAIAAAVIgJAAIAAgzIATAAQARAAAAAPQAAANgNABIAPAWgAgHgDIAGAAQANAAAAgIQAAgHgMAAIgHAAg");
	this.shape.setTransform(42.7,19.4,0.328,0.328);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AjnEaQgVgDgGgEQgKgFAAgNQAAgKAFgHQAHgHAIAAIARAAQAKAAAFgLQACgKABgXIAAl5QgBgXgCgKQgFgLgKAAIgRAAQgIAAgHgHQgFgHAAgKQAAgNAKgFQAGgEAVgDQBdgNBrAAQBOAAA2ASQA0ASAnAoQAlAlAUA5QAUA4AABEQAABNgZA9QgaA+guAlQglAegxAOQgwAOhFAAQhrAAhdgNgAgwjrQgcAFgJALQgKAMAAAhIAAFjQAAAhAUALQAOAHAnADQBMAEAthAQAqg/AAhwQAAhwgqg/Qgrg/hKAAIgeADg");
	this.shape_1.setTransform(20.4,9.9,0.328,0.328);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgNBlQgFgDAAgHIAAiTQAAgKgMAAIgyAAQgKAAAAgPIABgNQACgIAHAAICfAAQAMAAAAASQAAASgLAAIgyAAQgMAAAAAKIABCTQAAAHgFADQgEACgKAAQgJAAgEgCg");
	this.shape_2.setTransform(26.6,29,0.328,0.328);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhMBmQgNAAAAgPIAAiuQAAgOANAAICbAAQAGAAADAFQACADAAAJQAAAKgCADQgDAGgHAAIh5AAQgIAAAAAJIAAAbQAAAKAKAAIBFAAQALAAAAASQAAAQgKAAIhFAAQgLAAAAALIAAAeQAAAKAKAAIB4AAQAKAAAAATQAAARgKAAg");
	this.shape_3.setTransform(17.2,28.9,0.328,0.328);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAxBgIhAhGQgLgJgTAAQgFAAgEAEQgDAFAAAGIAAA8QAAAMgVAAQgRAAAAgNIAAi0QAAgIAFgCQAEgCALAAQASAAAAAMIAAA3QAAANAJAAQALAAAFgDQAEgBAFgFIBJhDQANgLAMAMQAMALgKAKIhAA6QgJAIAJAJIBOBWQAIAIgGAFQgFAFgNAAQgTAAgHgIg");
	this.shape_4.setTransform(7.4,28.9,0.328,0.328);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAuBeIgfgyQgGgJgKAAIgtAAQgDAAgEADQgEAEABADIAAAyQAAAGgKACIgPAAQgMAAAAgMIAAi5QgBgIAKAAIBqAAQAgAAAUATQAVATAAAfQAAAYgPAPQgIAJgPAKQgHAGADAGIAjAyQAFAIgFADQgEAFgPAAQgQAAgHgJgAg4g4IAAAuQAAAFAEADQAEACAFAAIA+AAQAQAAALgIQALgIAAgRQAAgQgLgJQgLgJgQABIg+AAQgNAAAAAKg");
	this.shape_5.setTransform(-3.6,29,0.328,0.328);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("ABCBgIgOgbQgCgHgHAAIhTAAQgJAAgEALIgMAXQgDAHgSAAQgWAAAFgMIBZi4QAFgKAKAAQALAAAFAJIBXC6QADAGgJAEQgGACgIAAQgPAAgDgIgAgEgdIgYAyQgDAIAIAAIAwAAQABAAABAAQAAAAABgBQABAAAAAAQAAgBABAAQACgCgCgDIgZgzQgBgDgEAAQgCAAgCADg");
	this.shape_6.setTransform(-14.5,28.9,0.328,0.328);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("ABZBkQgFgDAAgEIgOhsQgCgGgFAAQgDAAgDADIgxA+QgEAGgFAAQgHAAgEgHIgtg7QgCgDgEAAQgFAAgBAHIgOBoQgCALgTAAQgGAAgFgDQgGgDAAgFIAViwQACgJADgEQAEgEALAAQAKAAAFAJIA4BPQAFAHAEAAQAEAAAHgIIA7hQQAEgIALAAQAGAAADACQAEADACAIIAVC1QABALgXAAQgFAAgFgDg");
	this.shape_7.setTransform(-25.6,29,0.328,0.328);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AipF/QhPhTAAiLQAAhZAghEQAghCA6gnQAZgTAmgTQAmgTAngOQAKgDgDgJQgCgKgNADQg7ALgrgSQgWgJgdgRQghgUgJgEQgvgWg6AZQgVAJgMgLQgLgLAGgXQAXhWBDg3QBKg9BQAXQA0APAlA0QAmA2AfALQATAGgBAPQAAAOgRADQgaAFgjgRQgggPgdgbQgfgcgvgCQgsgCgbAVQgLAIADAHQAEAHAKgDQAggHAdAGQAoAIAbAgQAkAoAuAPQA4ASAugfIAZgWQANgNAMAEQAPAEgBAUQgBAUgTAZQgiAsg+AeQhFAjgeAdQgwAwgTA9QgPAzAABQQAAByAqBAQAqBABKAAQBKAAArhCQAqhBAAhwQAAhfgXg4QgZg6g2gVQgbgKAFgTQAFgUAhgEQA3gGA8AsQBoBOAACjQAACOhPBVQhQBUiHAAQiDAAhPhUg");
	this.shape_8.setTransform(4.8,-17.8,0.328,0.328);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("ABnDwQhFg1gYheIgBgCQgCgMgHAAQgGAAgCALIgBACQgYBfhGA1QhIA3hoAAQh+AAhMhQQhMhQAAiFQAAiHBMhRQBLhQCAAAQBpAABHA3QBHA2AXBgQACALAGAAQAHgBACgKIABgBQAXhgBGg1QBHg3BoAAQB/AABNBQQBMBPAACFQAACHhMBRQhNBRiBAAQhmAAhHg3gACniqQgpA/AABuQAABrApA/QAoA9BIAAQBGAAApg/QApg/AAhrQAAhsgqg+QgphAhHAAQhGAAgoA/gAmFiqQgoA/AABuQAABsAoA+QAoA9BIAAQBGAAApg/QApg/AAhrQAAhsgqg+QgphAhHAAQhGAAgoA/g");
	this.shape_9.setTransform(-6.9,9.9,0.328,0.328);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ai5EbQgWAAgJgFQgIgFAAgOQAAgKAGgHQAHgHAJAAIARAAQAKAAAEgLQADgJAAgYIAAl7QAAgXgDgKQgCgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgJQAAgOAJgGQAIgFAWAAIFvAAQAaAAAEAVIAMA7QAEAQgFAJQgFAJgMAAQgPAAgHgOQgEgFgFgNQgFgQgPgFQgNgEggAAIhtAAQghAAgJAJQgIAJAAAiIAABkQAAAaAIAFQAFADAdAAIBFAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAJgOAAQgTAAgEgXIAAgFQgCgNgIgDQgHgEgbAAIhFAAQgeAAgEAEQgIAFAAAZIAACLQAAAbACAGQAGALAMAAIATAAQAKAAAGAHQAGAHAAAKQAAAOgJAFQgIAFgYAAg");
	this.shape_10.setTransform(-32.2,9.9,0.328,0.328);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhTEbIgTgEQgIAAgKAJQgKAIgJAAQgLAAgGgHQgGgGgEgQIgVhUQgCgIAAgJQAAgMAHgIQAIgHAMAAQAMAAAJALIAMARQAWAfAhASQAiASAkAAQApAAAagVQAZgUAAgiQAAghgbgfQgbgdg/gsIhNg2QgSgPgTgWQgggmAAgzQAAg9ArgmQArgmBGAAQAlAAAjAIIAWAFIALACQAJAAALgIIAJgFQAEgCAFAAQASAAAGAYIAUBcQABAEAAAIQAAAIgHAGQgHAGgKAAQgMAAgLgOQgNgVgHgIQgGgGgOgLQgjgbgtAAQgcAAgSAPQgRAQAAAaQAAAXAJALQAMASAbAWIApAdQAzAkAWARQAXASAUAUQAWAWAMAfQAMAeAAAhQAABJgyAtQgzAthUAAQgzAAglgNg");
	this.shape_11.setTransform(36.1,9.9,0.328,0.328);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ah+EYQgLgJgHgYIhJjYQgBgFgEAAQgFAAgBAFIhNDYQgKAagHAHQgNAJgQAAQgTAAgKgJQgLgJgJgYIimm+QgKgagHgHQgHgHgUgFQgOgCgFgFQgFgFAAgLQAAgVAdgBICvAAQAcAAAAAYQAAAKgHAFQgHAFgRABQgOACgGAFQgGAFAAAJQAAAJADAKIBzFHQACAGAFgBQAEAAACgGIA/i2QAIgYgHgYIglhuQgEgJgHgFQgGgEgPgEQgNgDgGgGQgFgEAAgKQAAgaAdAAICnAAQAdAAAAAYQAAASgcAEQgRACgFAFQgGAFAAAMQAAAKAIAZIBfEsQACAFAEAAQAFAAABgGIBdk6QAEgLAAgJQAAgSgdgEQgbgCAAgVQAAgNAHgGQAIgFARgBIElAAQAVABAIAFQAIAFAAAOQAAAKgGAIQgGAGgJAAIgQAAQgLAAgFALQgCAIAAAZIAABtQAAAeAFAGQAGAHAXAAIB0AAQAXAAAHgIQADgDAAgHIABgdIAAhpQAAgbgDgGQgFgLgKAAIgQAAQgKAAgHgGQgGgIAAgKQAAgOAIgFQAJgFAWgBICaAAQAWABAJAFQAJAFAAAOQAAAKgHAIQgGAGgJAAIgSAAQgEAAgEADQgFADgBAFQgDAJAAAYIAAF9QAAAXADAKQABAFAFACQAEADAEABIASAAQAJAAAGAGQAHAIAAAJQAAAOgJAFQgIAGgXAAIiaAAQgWAAgIgGQgIgFAAgOQAAgJAGgIQAHgGAJAAIAQAAQAKAAAFgLQADgGAAgbIAAh8IgBgeQAAgHgDgEQgHgHgXAAIh0AAQgXAAgGAGQgFAHAAAdIAACCQAAAYACAJQAFALALAAIAQAAQAJAAAGAGQAGAIAAAKQAAAOgIAEQgIAGgVAAIiaAAQgWAAgJgGQgIgFAAgOQAAgJAGgIQAHgGAJAAIARAAQAEgBAFgDQAEgCABgFQADgGAAgbIAAl9QAAgwgkAEQgLABgHAKQgIAIgGAWIiHGzQgJAfgKALQgLALgTAAQgTAAgLgJg");
	this.shape_12.setTransform(-24.4,-12,0.328,0.328);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AihEbQgWAAgIgFQgIgFAAgOQAAgKAGgHQAGgGAJAAIARAAQAEAAAEgDQAEgEACgEQADgIAAgXIAAl/QAAgZgDgJQgDgLgLABIgRAAQgKgBgGgGQgHgHAAgLQAAgNAJgGQAJgFAWAAICcAAQAWAAAJAFQAJAGAAANQAAALgGAHQgHAGgJABIgSAAQgOgBgDALQgDAGAAAcIAAFjQAAAdACAJQACAJAIAFQAGAEALACQALACAagBIAwAAQAvAAAPgfIAIgPQAIgQAPgBQAMAAAFAJQAFAJgEAQIgNBCQgEAVgaAAg");
	this.shape_13.setTransform(22.7,-12.2,0.328,0.328);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AjREWQgIgGAAgOQAAgJAGgHQAGgGAJAAIARAAQAEAAAEgEQAEgDABgEQAEgIAAgaIAAl7QAAgZgEgIQgBgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgKQAAgNAJgGQAIgFAWAAIFSAAQAZAAAFAVIAMA7QADAQgFAJQgFAIgMAAQgPAAgGgNQgDgCgGgQQgGgQgPgFQgMgEggAAIhQAAQghAAgJAJQgIAJAAAiIAABkQAAAaAIAFQAEADAeAAIAmAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAIgOAAQgTAAgEgWIAAgFQgCgNgIgDQgHgEgbAAIgmAAQgeAAgEAEQgIAFAAAZIAABsQAAAiADALQADALAKAEQAPAFAiAAIBVAAQAvAAAPgfIAHgQQAIgQAPAAQAMAAAFAJQAFAJgDAQIgNBCQgDALgHAFQgHAFgOAAIlhAAQgWAAgIgFg");
	this.shape_14.setTransform(37.5,-12.2,0.328,0.328);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#0C6E47").s().p("AqoZNQk7iFjyjyQjyjziFk6QiJlFAAljQAAlkCJlFQCFk6DyjzQDzjyE6iFQFFiJFjAAQFkAAFFCJQE6CFDyDyQDyDzCGE6QCJFFAAFkQAAFjiJFFQiGE6jyDzQjyDyk6CFQlFCJlkAAQljAAlFiJg");
	this.shape_15.setTransform(0,0,0.328,0.328);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.kalelogo, new cjs.Rectangle(-57.3,-57.3,114.7,114.7), null);


(lib.holidayplatterssmall = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AggAmQgPgPAAgWQAAgWAPgQQAPgPAWAAQAUAAALALQAMALAAATQAAAHgCACQgCABgIAAIgmAAQgDAAgCgBQAAgBgBAAQAAgBAAAAQAAgBgBAAQAAgBAAgBQAAAAAAgBQABgBAAAAQAAAAAAgBQABAAAAAAQACgCADAAIAVAAIAFgBQAAAAAAAAQABgBAAAAQAAAAAAgBQAAAAAAgBQAAgKgGgHQgHgGgJAAQgMAAgGALQgGAKAAAPQAAAPAJAMQAIALAMAAQAHAAAFgBQAGgCAEgEIAEgDQAFgEADAAQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAADgCADIgHAHQgJAHgIAEQgIADgKAAQgVAAgOgPg");
	this.shape.setTransform(164.4,2.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AgeAzQgFgCAAgFQAAgEAFgBIADgBQACgCABgDQACgDAAgIIgBgHIAAgIIAAgGIAAgYQgBgFgCgBIgFgDQgGgBAAgEQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBIAGgEIAOgEIAJgCQAFAAABAOIAAACIABAAQAFgHAFgFQAGgEAGAAQAHAAAEAEQAEAFAAAGQAAAIgDADQgDAFgGAAIgFgBIgEgEIgDgDQAAgBAAgBQgBAAAAAAQAAgBAAAAQgBAAAAAAQgHAAgDAKQgCAKAAAdIABAOQABAEADABIAEACQAGABAAAFQAAAEgGACQgFABgNAAQgQAAgFgBg");
	this.shape_1.setTransform(155.4,2.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AgkAmQgPgPAAgXQAAgWAQgPQAPgPAWAAQAWAAAOAOQAOAOAAAXQAAAWgPAQQgQAQgVAAQgWAAgOgPgAgTgdQgGAHAAAOQAAATAJAOQAIANAMAAQAKABAGgJQAGgIAAgOQAAgTgJgOQgIgNgLAAQgKAAgHAJg");
	this.shape_2.setTransform(145.6,2.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AAmBHQgGgBAAgFQAAgEAHgCIAEgDQACAAABgFIAAgSIAAgGIAAgqIAAgZIgNAhQgeBNgGAAQgDAAgGgKQgGgLgOghIgWgzIgBAoIgBAbIABATQABAFABAAIAFADQAGACAAAEQAAAFgFABQgFACgNAAQgLAAgFgCQgFgBAAgFQAAgDAGgDQAFgDABgCQABgEACgaQABgaAAggIAAgDQAAgLgBgEQgBgDgCgBIgFgCQgGgDAAgEQAAgFAEgBQAFgCAPAAIAOABIAEABQACABAHASIAGAPIADAHQAZA9ABAAQACAAAJgXQAJgVANgjIACgHQAEgLADgDQABgCAEgBIAOgBQAOAAAEACQAFABAAAFQAAAEgGACIgDACQgDABgBAEQgBAEAAAPIABA6IACAdQABADAEACIACABIAEACQABAAAAABQAAAAAAAAQABABAAAAQAAABAAAAQAAAFgGABQgGACgQAAQgQAAgFgCg");
	this.shape_3.setTransform(130.7,0.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("Ag8A9QgUgOABgXQAAgOAFgKQAHgJANgJIABgBQgFgFgCgEQgCgFAAgFQAAgQALgLQAMgKASAAQANAAAIAFQAIAFABAGQAAAAgBABQAAAAAAABQAAAAgBABQAAAAgBABQgCACgCgBIgIgCQgHgCgGAAQgJAAgEAEQgFAGAAAJQAAADACADQAAADADADIAHAFIAGACIACABIABABQAAACgEAFQgEADgDAAIgFAAIgGgDQgGAFgDAGQgDAIAAAJQAAATANANQAMAMAUAAQAQAAAKgIQAKgIAAgOQAAgJgEgFQgEgFgHAAQgHAAgFAEQgEAFAAAFIAAACIAAABIgBABIgCABQgDgBgCgDQgCgDgBgEQAAgPAsgUIAEgCQALgFAHgGQAFgGAAgIQAAgEgCgCQgDgDgFAAIgEAAIgEABQAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAgBgBQAAAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgFAGgDQAFgCAJAAQALAAAGAFQAHAGAAAKQAAAOgMAKQgKAKgXAJQAKADAEAHQAFAIAAAKQAAAIgDAHQgDAIgFAFQgKALgOAFQgOAFgRAAQgfAAgSgPg");
	this.shape_4.setTransform(107.8,0.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AgHA0IgKgBIgEABIgDACIgCgBIgCgCQgDgCgDgJQgDgIAAgIQAAgDACgBQAAgBABgBQAAAAABAAQAAgBABAAQAAAAABAAQAFAAAEAIIAEAGQADAEAGADQAFACAFAAQAHAAAEgDQAEgEAAgFQAAgJgRgIIgFgDQgQgIgGgFQgFgHAAgKQAAgNAJgIQAJgJAPABIAGAAIAHABIAFgCIADAAQAFAAAFAIQAFAIAAAIQAAAEgCACQgBABAAAAQgBAAAAABQAAAAgBAAQgBAAAAAAQgDAAgCgCIgFgHQgEgGgEgDQgEgCgGAAQgFAAgEADQgDADAAAGQAAAFADADQAEADAMAHIABAAQAcANAAARQAAAOgKAKQgLAKgRAAg");
	this.shape_5.setTransform(88.6,2.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AggAmQgPgPAAgWQAAgWAPgQQAPgPAWAAQAUAAALALQAMALAAATQAAAHgCACQgCABgIAAIgmAAQgDAAgCgBQAAgBgBAAQAAgBAAAAQAAgBgBAAQAAgBAAgBQAAAAAAgBQABgBAAAAQAAAAAAgBQABAAAAAAQACgCADAAIAVAAIAFgBQAAAAAAAAQABgBAAAAQAAAAAAgBQAAAAAAgBQAAgKgGgHQgHgGgJAAQgMAAgGALQgGAKAAAPQAAAPAJAMQAIALAMAAQAHAAAFgBQAGgCAEgEIAEgDQAFgEADAAQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAADgCADIgHAHQgJAHgIAEQgIADgKAAQgVAAgOgPg");
	this.shape_6.setTransform(79,2.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AgFA9QgEgCgEgDQgDgDgCgGQgBgFAAgQIAAg1IgKAAIgDgBIgBgCIAAgDQAAgDALgJIAEgEIAEgEQAKgJAEAAIACABIABACIAAAUIAYAAIADABIABADIAAADIgBAEQAAAAgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAIgWAAIgBAAIgBADIAAAyQAAANACADQADADAFAAQAEAAAFgBIAHgCQABAAAAAAQAAAAABAAQAAABABAAQAAAAAAABQABAAAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAAFgIAFQgJAGgLAAQgGAAgFgCg");
	this.shape_7.setTransform(70.1,1.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AgRBJQgGgCAAgFQABgDAEgCIADgBQADgBABgEIABgLIAAgHIAAgIIAAgLQAAgQgBgDQAAgFgDgBIgEgCQgHgCAAgEQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAAAgBIAGgDIAQgFIAJgCQABAAABAAQAAAAABABQAAAAABAAQAAAAAAABQACACAAAFIAAAGIAAAEIgBAZIAAABIgBAZIACAOQABAEACABIADABQAGACAAAEQAAAEgGACQgFABgNAAQgPAAgEgBgAgMgyQgEgEAAgFQAAgGAFgEQAEgEAHAAQAGAAAEADQAFAEAAAGQAAAFgFAEQgFAEgGAAQgHAAgEgDg");
	this.shape_8.setTransform(63.5,0.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AgHBKIgTgBIgKAAIgMABQgHAAgDgCQgEgDAAgDQAAgEAFgCQAGgCABgCQABgCABgPIABgnIgBgmQgBgPgBgCQgBgBgGgDQgFgCAAgEQAAgEADgBQADgCAGAAIALAAIAMAAIAUgBIAQAAQAWAAALAJQAMAKAAAQQAAAPgIAIQgJAJgQACQAVADALAIQAKAKAAARQAAATgNALQgOAKgYAAgAgPg6QgDABgBABIgCANIgBAdIAAAqIABAUIACAIQABACAFABQAFABAIAAQARAAAJgGQAIgIAAgNQAAgOgKgHQgKgHgRAAQgJAAAAgFQAAgIAIABQANgBAJgGQAIgFAAgOQAAgNgIgGQgIgHgPAAg");
	this.shape_9.setTransform(53.6,0.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("AgRBJQgEgCAAgEQAAgDAEgCIAFgDQACgCAAgGIABgUIAAgQIAAgSIAAgIQAAgZgBgIQgBgHgCgBIgGgDQgHgBAAgEQAAgBABAAQAAgBAAAAQAAgBABAAQAAgBABAAIAJgEIANgEIAKgCQABAAAAAAQABAAAAABQABAAAAAAQABABAAAAQABACAAAFIAAAIIgBBIIABAjQABAHABACIAGADQAEACAAAEQAAAEgEABQgGACgNAAQgOAAgGgCg");
	this.shape_10.setTransform(38.2,0);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AgRBJQgEgCAAgEQgBgDAFgCIAFgDQABgCACgGIAAgUIAAgQIAAgSIAAgIQAAgZgBgIQgBgHgCgBIgGgDQgGgBgBgEQAAgBABAAQAAgBAAAAQAAgBABAAQAAgBAAAAIAJgEIAPgEIAJgCQABAAAAAAQABAAABABQAAAAAAAAQABABAAAAQACACAAAFIgBAIIgBBIIABAjQABAHABACIAFADQAGACgBAEQABAEgGABQgEACgOAAQgPAAgFgCg");
	this.shape_11.setTransform(32.5,0);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AASAwIgFgFIgFABQgMAJgMAAQgPAAgJgJQgJgJAAgNQAAgRALgHQAMgKAVAAQAFAAACACQADABAAAEQAAAFgGAAQgKAAgGAFQgHAFAAAIQAAAIAGAGQAFAEAJAAQAJABAEgFQAEgFAAgKIAAgmQAAgJgDgFQgEgEgHAAQgFAAgEACQgEACgEAFIgCACQgGAIgHAAQgEAAgDgCQgCgDAAgEQAAgKAMgHQALgGATAAQAKAAAIADQAJACAEAHQADADABAHQACAGAAAPIAAAfIABAJQAAABAAAAQABABAAAAQAAAAABABQAAAAABAAIADABQAGACAAADQAAAFgHAEQgGAEgKAAQgEAAgFgFg");
	this.shape_12.setTransform(24.5,2.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("AAtAzQgFgCAAgEQAAgEAFgCIAEgCQACgBACgFIAAgRQAAgdgDgJQgFgHgKgBQgMAAgFALQgGAKAAAYIAAAFQAAAMACADQABADADACIACABQAFABAAAEQAAAFgFABQgEACgQAAQgNAAgFgBQgFgCAAgEQAAgEAFgCIAEgCQADgBABgEIAAgQQAAgfgEgJQgEgHgLgBQgGABgEADQgFADgCAGQgDAEgBAIIgBAbIABANQABADACABIAEACQAFACAAAEQAAAEgFACQgFABgOAAQgPAAgEgBQgFgCgBgFQABgEAFgBIACgBQACgCACgDIABgLIAAgHIAAgIIAAgGQAAgSgBgGQgBgFgDgBIgEgDQgGgBAAgEQAAgBAAAAQAAAAABgBQAAAAAAgBQABAAAAgBIAGgDIAPgGIAKgBQABAAAAAAQABAAAAAAQABABAAAAQABAAAAAAQABACAAAEIAAAFIAAACIABABIAAAAIABAAIABgBIACgCIABgBQAMgLANAAIAJABIAJAFIAGAHIAEAEQACAAADgDIAFgFQAGgFAFgCQAEgCAGAAQANAAAIAFQAJAEAEAJQAFAJAAAdIAAAKIAAAFIAAAGIABAIQAAADADABIACABQAGABAAAEQAAAFgFABQgEACgRAAQgOAAgFgBg");
	this.shape_13.setTransform(9.5,2.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("AgYBJQgMgCgHgFQgEgCgDgJQgCgIAAgMQAAgEACgDQABgCAEAAQAEAAAFAJIADAEQAGALAIAGQAIAFAKAAQALAAAHgHQAIgGAAgKQAAgOgegOIgDgBQgYgKgIgJQgJgJAAgOQAAgSAOgMQANgMAWAAIALABIAOADIAEgCIAEgBQAAAAABAAQABAAAAAAQABAAAAABQABAAAAAAIAEAGQAEAGACAHQACAGAAAFQAAAEgCACQAAAAgBAAQAAABgBAAQAAAAgBAAQgBAAAAAAQgGAAgFgHIgBgCQgGgHgHgEQgHgEgIAAQgLAAgGAGQgHAFAAAJQAAAIAGAGQAFAGAVAJIAEACQATAHAIAHQAFAFADAHQADAHAAAIQAAAUgOAMQgPAMgZAAQgMAAgLgDg");
	this.shape_14.setTransform(-5.6,0.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("AgKAfIgCgCIACgEIACgDIAGgMIACgHIgBgCIgDgBQgFgCgDgEQgCgEAAgFQAAgHAEgFQAEgEAGAAQAGAAAFAGQAEAGAAAJQAAAHgCAGQgDAIgHAKIgEAIQgBABAAABQgBAAgBAAQAAABAAAAQgBAAAAAAIgFgBg");
	this.shape_15.setTransform(-19.6,7.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E47").s().p("AgHA0IgKgBIgEABIgDACIgCgBIgCgCQgDgCgDgJQgDgIAAgIQAAgDACgBQAAgBABgBQAAAAAAAAQABgBABAAQAAAAABAAQAFAAAEAIIAEAGQADAEAGADQAFACAFAAQAHAAAEgDQAEgEAAgFQAAgJgRgIIgFgDQgQgIgGgFQgFgHAAgKQAAgNAJgIQAJgJAPABIAGAAIAHABIAFgCIADAAQAFAAAFAIQAFAIAAAIQAAAEgCACQgBABAAAAQAAAAgBABQAAAAgBAAQgBAAAAAAQgDAAgCgCIgFgHQgEgGgEgDQgEgCgGAAQgFAAgEADQgDADAAAGQAAAFADADQAEADAMAHIABAAQAcANAAARQAAAOgKAKQgLAKgRAAg");
	this.shape_16.setTransform(-27.1,2.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E47").s().p("AgeAzQgFgCAAgFQAAgEAFgBIADgBQACgCABgDQACgDAAgIIgBgHIAAgIIAAgGIAAgYQgBgFgCgBIgFgDQgGgBAAgEQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBIAGgEIAOgEIAJgCQAFAAABAOIAAACIABAAQAFgHAFgFQAGgEAGAAQAHAAAEAEQAEAFAAAGQAAAIgDADQgDAFgGAAIgFgBIgEgEIgDgDQAAgBAAgBQgBAAAAAAQAAgBAAAAQAAAAgBAAQgHAAgDAKQgCAKAAAdIABAOQABAEADABIAEACQAGABAAAFQAAAEgGACQgFABgNAAQgQAAgFgBg");
	this.shape_17.setTransform(-35.1,2.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#006E47").s().p("AggAmQgPgPAAgWQAAgWAPgQQAPgPAWAAQAUAAALALQAMALAAATQAAAHgCACQgCABgIAAIgmAAQgDAAgCgBQAAgBgBAAQAAgBAAAAQgBgBAAAAQAAgBAAgBQAAAAAAgBQAAgBABAAQAAAAAAgBQABAAAAAAQACgCADAAIAVAAIAFgBQAAAAAAAAQABgBAAAAQAAAAAAgBQAAAAAAgBQAAgKgGgHQgHgGgJAAQgMAAgGALQgGAKAAAPQAAAPAJAMQAIALAMAAQAHAAAFgBQAGgCAEgEIAEgDQAFgEADAAQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAADgCADIgHAHQgJAHgIAEQgIADgKAAQgVAAgOgPg");
	this.shape_18.setTransform(-44.5,2.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#006E47").s().p("AgFA9QgEgCgEgDQgEgDgBgGQgCgFAAgQIAAg1IgJAAIgDgBIgBgCIAAgDQAAgDALgJIAEgEIAEgEQAKgJAEAAIADABIAAACIAAAUIAYAAIADABIABADIAAADIgBAEQAAAAgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAIgWAAIgBAAIgBADIAAAyQAAANACADQADADAFAAQAEAAAFgBIAHgCQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABQABAAAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAAFgJAFQgIAGgLAAQgGAAgFgCg");
	this.shape_19.setTransform(-53.4,1.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#006E47").s().p("AgFA9QgEgCgEgDQgEgDgBgGQgCgFAAgQIAAg1IgJAAIgDgBIgBgCIAAgDQAAgDALgJIAEgEIAEgEQAKgJAEAAIADABIAAACIAAAUIAYAAIADABIABADIAAADIgBAEQAAAAgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAIgWAAIgBAAIgBADIAAAyQAAANACADQADADAFAAQAEAAAFgBIAHgCQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABQABAAAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAAFgJAFQgIAGgLAAQgGAAgFgCg");
	this.shape_20.setTransform(-60.6,1.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#006E47").s().p("AASAwIgFgFIgFABQgMAJgMAAQgPAAgJgJQgJgJAAgNQAAgRALgHQAMgKAVAAQAFAAACACQADABAAAEQAAAFgGAAQgKAAgGAFQgHAFAAAIQAAAIAGAGQAFAEAJAAQAJABAEgFQAEgFAAgKIAAgmQAAgJgDgFQgEgEgHAAQgFAAgEACQgEACgEAFIgCACQgGAIgHAAQgEAAgDgCQgCgDAAgEQAAgKAMgHQALgGATAAQAKAAAIADQAJACAEAHQADADABAHQACAGAAAPIAAAfIABAJQAAABAAAAQABABAAAAQAAAAABABQAAAAABAAIADABQAGACAAADQAAAFgHAEQgGAEgKAAQgEAAgFgFg");
	this.shape_21.setTransform(-69.6,2.4);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#006E47").s().p("AgRBJQgEgCAAgEQgBgDAFgCIAFgDQABgCABgGIABgUIAAgQIAAgSIAAgIQAAgZgBgIQgBgHgCgBIgGgDQgGgBgBgEQAAgBABAAQAAgBAAAAQAAgBABAAQAAgBAAAAIAJgEIAOgEIAKgCQABAAAAAAQABAAABABQAAAAAAAAQABABAAAAQABACABAFIgBAIIgBBIIABAjQAAAHACACIAGADQAEACAAAEQAAAEgEABQgGACgNAAQgOAAgGgCg");
	this.shape_22.setTransform(-78.1,0);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#006E47").s().p("Ag0BIQgGgBAAgFQAAgEAHgDIAEgCQACgCABgMIABgrIgBgmQAAgPgCgCQgBgBgFgDQgGgCAAgEQAAgEAEgBQADgCAGAAIALAAIALAAIAVgBIAPAAQAXAAALAKQAMAKAAATQAAAWgOAKQgOALgbAAQgKAAAAgHQAAgGAIgBQANAAAIgGQAIgHAAgPQAAgOgIgGQgIgHgQAAIgKABQgDABgBADIgBAJIgBAWIAAAsIABAcQAAAIACABIAFACQAGADAAAEQAAAFgGABQgFACgQAAQgQAAgGgCg");
	this.shape_23.setTransform(-86.7,0.1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#006E47").s().p("AguBDQgFgEAAgGQAAgGADgDQAEgEAFAAIAFABIADACIADAEQADAEABAAQAFAAAGgHQAFgIAAgIQAAgJgHgQIgBgCIgRgjIgJgUQgBgDgHgDIAAAAQgDgBgBgCQAAAAgBgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQgBgFAGgCQAFgBAPAAQAPAAAFABQAFACAAAEIgBADIgBACIgEACQgBAAgBABQAAAAgBAAQAAABgBAAQAAAAAAABIACAIIAIAUIAHATQADAFACAAQABAAACgFIAHgQIAHgUIADgKQgBgDgFgDQgGgDAAgDQAAgDAFgCQAEgBAMAAQAMAAAFABQADACAAAEQAAAEgFABIgFACQgFADgGARIgEAIIgMAgQgRAqgKANQgLAMgPAAQgHAAgFgEg");
	this.shape_24.setTransform(-103.6,4.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#006E47").s().p("AASAwIgFgFIgFABQgMAJgMAAQgPAAgJgJQgJgJAAgNQAAgRALgHQAMgKAVAAQAFAAACACQADABAAAEQAAAFgGAAQgKAAgGAFQgHAFAAAIQAAAIAGAGQAFAEAJAAQAJABAEgFQAEgFAAgKIAAgmQAAgJgDgFQgEgEgHAAQgFAAgEACQgEACgEAFIgCACQgGAIgHAAQgEAAgDgCQgCgDAAgEQAAgKAMgHQALgGATAAQAKAAAIADQAJACAEAHQADADABAHQACAGAAAPIAAAfIABAJQAAABAAAAQABABAAAAQAAAAABABQAAAAABAAIADABQAGACAAADQAAAFgHAEQgGAEgKAAQgEAAgFgFg");
	this.shape_25.setTransform(-114.1,2.4);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#006E47").s().p("AAUBKQgBgCAAgEIAAgEIAAgDIgBAAIgDACIgFAEQgGAEgEACQgGACgHAAQgTAAgMgOQgMgNAAgWQAAgZAOgPQAOgPAWAAIAGAAQADABACADQABAAAAABQAAABAAAAQABABAAAAQAAABAAAAQAAAGgHAAIgCAAIgDAAQgLAAgHAJQgHAIAAAQQAAARAIALQAHALAMAAQAJAAAGgGQAGgGAAgMIAAgbIAAguQAAgHgBgDQgBgDgEgBIgDgBQgGgCAAgDQAAgDACgCIAKgFIAMgDIAJgBQAEAAABABQACADAAAEIAAAGIgCA9IABArQABAKABABIAHACQAGACAAADQAAAEgPAGIgKACIgIABQgBAAAAAAQgBAAAAAAQgBgBAAAAQgBAAAAAAg");
	this.shape_26.setTransform(-125.3,0.1);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#006E47").s().p("AgRBJQgGgCAAgFQABgDAFgCIACgBQADgBABgEIABgLIAAgHIAAgIIAAgLQAAgQgBgDQgBgFgCgBIgEgCQgHgCAAgEQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAAAgBIAGgDIAQgFIAKgCQAAAAABAAQAAAAABABQAAAAABAAQAAAAAAABQACACAAAFIAAAGIgBAEIAAAZIAAABIgBAZIABAOQACAEACABIADABQAGACAAAEQAAAEgGACQgEABgOAAQgOAAgFgBgAgMgyQgEgEAAgFQAAgGAFgEQAEgEAHAAQAGAAAEADQAEAEABAGQAAAFgFAEQgFAEgGAAQgHAAgEgDg");
	this.shape_27.setTransform(-134.6,0.1);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#006E47").s().p("AgRBJQgEgCgBgEQAAgDAFgCIAFgDQACgCABgGIAAgUIAAgQIAAgSIAAgIQAAgZgBgIQgBgHgCgBIgGgDQgGgBgBgEQAAgBABAAQAAgBAAAAQAAgBABAAQAAgBAAAAIAJgEIAPgEIAJgCQABAAAAAAQABAAABABQAAAAAAAAQABABAAAAQACACAAAFIgBAIIgBBIIAAAjQACAHABACIAFADQAGACAAAEQAAAEgGABQgEACgOAAQgPAAgFgCg");
	this.shape_28.setTransform(-140.4,0);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#006E47").s().p("AgkAmQgPgPAAgXQAAgWAQgPQAPgPAWAAQAWAAAOAOQAOAOAAAXQAAAWgPAQQgQAQgVAAQgWAAgOgPgAgTgdQgGAHAAAOQAAATAJAOQAIANAMAAQAKABAGgJQAGgIAAgOQAAgTgJgOQgIgNgLAAQgKAAgHAJg");
	this.shape_29.setTransform(-148.8,2.4);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#006E47").s().p("AAXBHQgGgBAAgFQAAgEAGgCIAFgDQACAAAAgHIABgYIAAgOIgBgEQgBgCgFgBIgYAAIgVAAQgFAAgCACIgBADIgBAHIAAAJIABAYQABAHABAAIAFADQAGACAAAEQAAAFgGABQgFACgQAAQgQAAgGgCQgGgBAAgFQAAgEAHgCIAEgDQACgBABgNIABgqIgBgmQAAgQgCgBQgBgCgFgCQgGgCAAgEQAAgFAFgBQAFgCASAAQASAAAEACQAFABAAAFQAAAEgGADIgFACQgCABAAAGIgBAeQAAAEAEACQAEABAOAAIAIAAIAVAAQAHgBACgCIABgCIAAgDIAAgFIgBgZQAAgFgCgBIgFgCQgGgDAAgEQAAgFAFgBQAFgCARAAQATABAEABQAFABAAAFQAAAEgHADIgEACQgCABgBAOIgBApIABAmQABAQABABQABACAFADQAGABAAAEQAAAFgGABQgGACgQAAQgQAAgFgCg");
	this.shape_30.setTransform(-162.2,0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidayplatterssmall, new cjs.Rectangle(-171.9,-14,343.8,28.2), null);


(lib.greyrectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#999999").ss(1,1,1).p("Eg3igGjMBvFAAAIAANHMhvFAAAg");
	this.shape.setTransform(0,0,1.023,1.06);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.greyrectangle, new cjs.Rectangle(-364.5,-45.5,729,91), null);


(lib.getpartystartednineteen = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AgkAsIgEgBQAAAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBIAAhPQAAAAAAAAQAAgBAAAAQAAgBABAAQAAAAAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAAAIAhAAIAIABIAJACQAJADAGAGQAHAGADAIIADAJIABAIQAAAKgEAIIgEAHIgGAHIgHAFIgIAEQgJADgIAAgAgXgaQgBAAAAABQAAAAAAABQgBAAAAABQAAAAAAAAIAAAwQAAAAAAABQAAAAABAAQAAABAAAAQAAAAABABIADABIAQAAQAFAAAGgCQAFgDAFgDQAEgDACgGQADgFAAgHQAAgFgDgGQgCgFgEgEQgFgDgFgCQgGgCgFgBIgQAAQAAAAgBABQAAAAgBAAQAAAAAAAAQgBABAAAAg");
	this.shape.setTransform(77.1,-0.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AgdAsIgDgBIgCgCIAAhRQABAAAAAAQAAgBAAAAQAAAAAAAAQABgBAAAAIACgBIA9AAIADACIABACIAAAEIAAACIgBADIgDACIgtAAIgCACIgBADIAAALIABAEIADABIAdAAIACABIABACIAAAEIAAACQAAAEgDAAIgdAAIgCACQgBAAAAABQAAAAgBABQAAAAAAABQAAAAAAABIAAAMIABAEQAAAAABAAQAAAAAAABQABAAAAAAQABAAAAAAIAsAAQADABAAADIABAEIgBADIgBADIgCABg");
	this.shape_1.setTransform(67.8,-0.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AACAsIgDAAIgEgBQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAhAQAAgBAAAAQAAgBAAAAQAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAAAAAQgBAAgBAAQAAAAgBAAIgHAAIgHAAIgDAAQgBAAAAAAQgBgBAAAAQgBAAAAAAQgBgBAAAAIgBgEIAAgDIABgDIABgCIADgBIA8AAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABIABADIAAADIgBADIgBADIgCABIgSAAIgDABQgBAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAIAABAIgBADIgCABg");
	this.shape_2.setTransform(59.5,-0.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AAWAtIgCgBIgCgBIgBgBIgPgXIgCgDIgEgBIgLAAIgDABIgBADIAAAWQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAAAAAIgEABIgDABIgDAAIgEgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgBAAAAIAAhQQAAgBAAAAQAAAAAAgBQAAAAAAAAQABgBAAAAIACgBIAlAAQAHAAAGACQAFADAFADQAEAEACAGQACAFAAAHQAAAIgCAEQgDAEgDADIgHAFQAAAAgBABQAAAAgBAAQAAABAAAAQgBABAAAAIAAACIAEAFIAFAHIAFAHIACAFIgBACIgDACIgDABIgDABgAgRgbQgBAAAAAAQgBABAAAAQAAABAAAAQAAABAAAAIAAAUQAAAAAAABQAAAAAAABQAAAAABABQAAAAABABIADAAIASAAIAGAAIAGgDQACgBABgDQACgDgBgEQAAgHgEgEIgGgCIgGgBIgSAAIgDABg");
	this.shape_3.setTransform(51.7,-0.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AAjAsIgDAAIgEAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQgBgBAAAAIgFgMIgBgCIgDgBIgdAAIgBABIgBAAIgBABIgBABIgFAMIgCACIgCAAIgDABIgCAAIgCAAIgDAAIgCgBQgBAAAAAAQAAgBAAAAQgBAAAAAAQAAgBAAAAIAlhSIACgCIACgBIAEAAQAAABABAAQAAAAABAAQAAABAAAAQABABAAAAIAjBSIAAABIgBABIgDABgAAAgNIgBABIgBACIgCAEIgCAFIgCAFIgCADIAAACIAAACIACABIARAAIACgBIABgCIgCgDIgDgHIgDgHIgCgEIgCgBg");
	this.shape_4.setTransform(42.5,-0.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AACAsIgDAAIgEgBQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAhAQAAgBAAAAQAAgBAAAAQAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAAAgBAAIgHAAIgHAAIgDAAQgBAAAAAAQgBgBAAAAQgBAAAAAAQgBgBAAAAIgBgEIAAgDIABgDIABgCIADgBIA8AAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABIABADIAAADIgBADIgBADIgCABIgSAAIgDABQgBAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAIAABAIgBADIgCABg");
	this.shape_5.setTransform(34.6,-0.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AgTAqQgKgDgHgHIgBgCIAAgBIABgDIADgDIADgCIADgBIAEABIAGAEIAHAEQAEABAGAAIAGAAIAHgCIAFgEQACgDAAgEQAAgDgCgCQgDgDgDgBIgKgBIgJgCIgKgCQgFgBgEgCQgEgDgDgEQgCgFAAgGQAAgHADgFQAEgFAFgEQAFgDAHgBIALgCIAJABIAIACIAJADIAHAFIAAACIABABIgBADIgDADIgDACIgEABIgCAAQgFgEgFgDQgFgCgGAAIgGAAIgGACIgEAEQgCACAAAEQAAAFAEACIAKADIANACQAHABAHACQAGADAEADQAFAFAAAJQgBAIgDAGQgEAFgFAEQgGADgHACIgMACQgKAAgJgEg");
	this.shape_6.setTransform(26.7,-0.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AAAAuIgDAAIgCAAIgCgCIAAgCIAAgeIgBgGIgCgEIgZgnIAAgBIABgCIACgCIAEgCIADgBIACABIACACIASAdIACABIABAAIACAAIACgBIARgdIACgCIAEgBIACAAIADACIAEACIABACIAAABIgBABIgZAnIgCAFIgBADIAAABIAAAfQgCADgCABg");
	this.shape_7.setTransform(14.7,-0.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AACAsIgDAAIgEgBQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAhAQAAgBAAAAQAAgBAAAAQAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAAAgBAAIgHAAIgHAAIgDAAQgBAAAAAAQgBgBAAAAQgBAAAAAAQgBgBAAAAIgBgEIAAgDIABgDIABgCIADgBIA8AAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABIABADIAAADIgBADIgBADIgCABIgSAAIgDABQgBAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAIAABAIgBADIgCABg");
	this.shape_8.setTransform(7.1,-0.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AAWAtIgCgBIgBgBIgCgBIgPgXIgCgDIgEgBIgLAAIgDABIgCADIABAWQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgDABIgDABIgDAAIgEgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgBAAAAIAAhQQAAgBAAAAQAAAAAAgBQAAAAAAAAQABgBAAAAIACgBIAlAAQAHAAAGACQAFADAFADQAEAEACAGQACAFABAHQAAAIgEAEQgCAEgDADIgHAFQAAAAgBABQAAAAgBAAQAAABAAAAQAAABAAAAIAAACIADAFIAFAHIAFAHIACAFIgBACIgDACIgDABIgDABgAgRgbQgBAAAAAAQgBABAAAAQAAABAAAAQgBABAAAAIAAAUQAAAAABABQAAAAAAABQAAAAABABQAAAAABABIADAAIASAAIAHAAIAEgDQADgBABgDQABgDABgEQAAgHgGgEIgEgCIgHgBIgSAAIgDABg");
	this.shape_9.setTransform(-0.7,-0.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("AAjAsIgDAAIgEAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQgBgBAAAAIgFgMIgBgCIgDgBIgdAAIgBABIgBAAIgBABIgBABIgFAMIgCACIgCAAIgDABIgCAAIgCAAIgDAAIgCgBQgBAAAAAAQAAgBAAAAQgBAAAAAAQAAgBAAAAIAlhSIACgCIACgBIAEAAQAAABABAAQAAAAABAAQAAABAAAAQABABAAAAIAjBSIAAABIgBABIgDABgAAAgNIgBABIgBACIgCAEIgCAFIgCAFIgCADIAAACIAAACIACABIARAAIACgBIABgCIgCgDIgDgHIgDgHIgCgEIgCgBg");
	this.shape_10.setTransform(-9.9,-0.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AgeAtQgEAAgCgEIAAhSIACgCIACgBIAmAAQAGAAAFACQAGACAEAEQAFADACAFQADAFAAAHIgBAEIgBAEQgDAIgGAEQgGAEgHABQgHABgHAAIgPAAIgBAAIgBABIgCADIAAAcIgCACIgCAAIgDABgAgSgbQgBABAAAAQAAAAAAABQgBAAAAABQAAAAAAABIAAAOIACADIACABIAWAAIAFgBIAEgCQADgBABgDIABgFIgBgFIgDgDIgFgDIgEAAIgWAAQgBAAAAAAQgBAAAAAAQAAAAgBABQAAAAAAAAg");
	this.shape_11.setTransform(-18,-0.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AgdAsIgDgBIgCgCIAAhRQAAAAABAAQAAgBAAAAQAAAAAAAAQABgBAAAAIADgBIA9AAIACACIABACIAAAEIAAACIgBADIgCACIguAAIgCACIgBADIAAALIABAEIADABIAdAAIABABIABACIABAEIAAACQAAAEgDAAIgcAAIgEACQAAAAAAABQAAAAgBABQAAAAAAABQAAAAAAABIAAAMIABAEQAAAAABAAQAAAAAAABQABAAAAAAQABAAAAAAIAtAAQACABAAADIABAEIgBADIgBADIgCABg");
	this.shape_12.setTransform(-30.5,-0.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("AAbAtIgEAAIgDgCIAAggQAAAAAAgBQAAAAAAgBQAAAAgBAAQAAgBAAAAQgBgBAAAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgcAAQgBAAAAAAQgBAAgBABQAAAAAAAAQgBABAAAAQgBABAAAAQAAAAAAABQgBAAAAABQAAAAAAABIAAAeQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAgBABIgCAAIgEAAIgDAAIgDgBIgCgCIAAhTIACgCIADgBIADAAIADAAQAEAAABADIAAAcIABAEIADABIAeAAIAEgBQAAgBAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBIAAgcQACgDADAAIAFAAIAEABIACACIAABTQgBADgDAAg");
	this.shape_13.setTransform(-39.9,-0.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("AACAsIgDAAIgEgBQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAhAQAAgBAAAAQAAgBAAAAQAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAAAgBAAIgHAAIgHAAIgDAAQgBAAAAAAQgBgBAAAAQgBAAAAAAQgBgBAAAAIgBgEIAAgDIABgDIABgCIADgBIA8AAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABIABADIAAADIgBADIgBADIgCABIgSAAIgDABQgBAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAIAABAIgBADIgCABg");
	this.shape_14.setTransform(-48.4,-0.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("AACAsIgDAAIgEgBQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAhAQAAgBAAAAQAAgBAAAAQAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAAAgBAAIgHAAIgHAAIgDAAQgBAAAAAAQgBgBAAAAQgBAAAAAAQgBgBAAAAIgBgEIAAgDIABgDIABgCIADgBIA8AAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABIABADIAAADIgBADIgBADIgCABIgSAAIgDABQgBAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAIAABAIgBADIgCABg");
	this.shape_15.setTransform(-59.4,-0.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E47").s().p("AgdAsIgDgBIgCgCIAAhRQAAAAABAAQAAgBAAAAQAAAAAAAAQABgBAAAAIADgBIA9AAIACACIAAACIAAAEIAAACIAAADIgCACIgtAAIgDACIgBADIAAALIABAEIADABIAdAAIABABIABACIABAEIAAACQAAAEgDAAIgcAAIgEACQAAAAAAABQAAAAgBABQAAAAAAABQAAAAAAABIAAAMIABAEQAAAAABAAQAAAAAAABQABAAAAAAQAAAAABAAIAtAAQACABAAADIAAAEIAAADIgBADIgCABg");
	this.shape_16.setTransform(-66.9,-0.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E47").s().p("AgHAtIgIgDIgIgDIgIgGIgFgHIgFgHQgDgJAAgKIAAgIIADgJQAEgJAGgGIAIgFIAIgEIAIgDIAJgBQAFAAAFACIAKACQAJAFAHAHIAAACIgBADIgDADIgDACIgDACIgEgCIgFgEIgHgFQgEgCgGAAQgFABgGACQgFACgEAEQgFAFgCAFQgCAGAAAFQAAAGACAGQACAFAFAEQAEAEAFADQAGACAFABIAGgBIAGgBIAGgEQACgBACgDIAAgBIgBgDIgDgBIgQAAIgCgBIgBgDIAAgDIAAgDIAAgDQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAABAAIAlAAIABABIABABQACADAAAFIAAADIgBAEIgHAMQgEAFgGAEQgFADgHACQgGACgHAAIgJgBg");
	this.shape_17.setTransform(-76.9,-0.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.getpartystartednineteen, new cjs.Rectangle(-83.9,-8.4,167.9,16.9), null);


(lib.getinspired = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAaA1IgZhUIgBAAIgZBUIgQAAIgehpIAQAAIAXBUIAZhUIAQAAIAYBUIABAAIAXhUIAQAAIggBpg");
	this.shape.setTransform(34.1,0.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgLA3IgLgDQgKgEgHgIQgIgHgEgKQgEgLAAgMQAAgLAEgLQAEgKAIgHQAHgIAKgEIALgDIALgBQAMAAAKAEQAGACAEADIAIAHQAIAHAEAKQAEALAAALQAAAMgEALQgEAKgIAHIgIAHQgEADgGACQgKAEgMAAIgLgBgAgQgmQgHADgFAGQgGAGgCAIQgDAHAAAIQAAAJADAIQACAHAGAGQAFAGAHADQAIAEAIAAQAJAAAIgEQAHgDAFgGQAFgGADgHQADgIAAgJQAAgIgDgHQgDgIgFgGQgFgGgHgDQgIgEgJAAQgIAAgIAEg");
	this.shape_1.setTransform(20.3,0.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAaA1Ig3hWIAABWIgPAAIAAhpIATAAIA3BUIAAAAIAAhUIAPAAIAABpg");
	this.shape_2.setTransform(8.2,0.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgiA1IAAhpIAgAAQAIAAAHABQAHACAFAEQAFADACAGQADAFAAAJQAAAHgDAGQgDAGgFADQgFADgHACQgHACgIAAIgQAAIAAAugAgTgGIAPAAIAJAAIAIgDIAFgGQACgDAAgEQAAgGgCgCQgCgEgDgCIgIgDIgIAAIgQAAg");
	this.shape_3.setTransform(-5.4,0.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgLA3IgLgDQgKgEgHgIQgIgHgEgKQgEgLAAgMQAAgLAEgLQAEgKAIgHQAHgIAKgEIALgDIALgBQAMAAAKAEQAGACAEADIAIAHQAIAHAEAKQAEALAAALQAAAMgEALQgEAKgIAHIgIAHQgEADgGACQgKAEgMAAIgLgBgAgQgmQgHADgFAGQgGAGgCAIQgDAHAAAIQAAAJADAIQACAHAGAGQAFAGAHADQAIAEAIAAQAJAAAIgEQAHgDAFgGQAFgGADgHQADgIAAgJQAAgIgDgHQgDgIgFgGQgFgGgHgDQgIgEgJAAQgIAAgIAEg");
	this.shape_4.setTransform(-16.6,0.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAbA1IAAgwIg1AAIAAAwIgPAAIAAhpIAPAAIAAAsIA1AAIAAgsIAPAAIAABpg");
	this.shape_5.setTransform(-28.4,0.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgTA0QgKgEgGgHIALgKQAFAFAFAEQAHADAHAAIAHgBQAEgBADgCQADgCABgEQACgDAAgFQAAgFgCgDQgCgDgDgCIgIgEIgIgEIgLgDQgEgBgFgEQgEgDgCgFQgCgFAAgHQAAgIADgGQADgGAGgDQAEgEAHgCQAGgCAHAAIAJABIAHADQAJADAFAFIgLALQgDgFgFgCQgGgDgHAAIgGABIgGADIgGAFQgBAEAAAEQAAAEABADIAFAFIAHAEIAIADIALADIAKAFQAEADADAGQADAFAAAIQAAAIgDAGQgEAGgEAEQgGAEgHACQgGACgGAAQgKAAgJgEg");
	this.shape_6.setTransform(-38.2,0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.getinspired, new cjs.Rectangle(-44.3,-11.2,88,22.4), null);


(lib.ctarectanglevideo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B63100").s().p("AnaCbQhBAAgtgtQgtgtAAhBIAAAAQAAhAAtgtQAtgtBBAAIO1AAQBBAAAtAtQAtAtAABAIAAAAQAABBgtAtQgtAthBAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ctarectanglevideo, new cjs.Rectangle(-63,-15.5,126.1,31.1), null);


(lib.ctarectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D63900").s().p("AnaCbQhBAAgtgtQgtgtAAhBIAAAAQAAhAAtgtQAtgtBBAAIO1AAQBBAAAtAtQAtAtAABAIAAAAQAABBgtAtQgtAthBAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ctarectangle, new cjs.Rectangle(-63,-15.5,126.1,31.1), null);


(lib.crowdplease = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AgIA/IgNgCIgEACIgEABIgCAAIgDgCQgEgDgDgKQgEgKAAgJQAAgEADgDQABgCADAAQAGAAAGAKIAEAHQAEAFAGADQAHACAGAAQAIAAAFgEQAFgEAAgHQgBgKgTgKIgHgDQgTgKgHgHQgGgIgBgLQAAgQALgKQAMgKARAAIAIAAIAIACIAHgCIADgBQAGAAAGAKQAGAJgBALQAAAEgCADQgBACgDAAQgDAAgDgCQgDgDgEgGQgEgHgFgDQgFgDgGAAQgHAAgEAEQgEAEgBAGQABAGAEAEQAEAEAPAIIABABQAiAQAAATQAAARgNAMQgNALgTAAg");
	this.shape.setTransform(171.1,2.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AgkA8QgGgBAAgGQAAgEAGgCIADgBQADgCABgEQACgEAAgKIgBgHIAAgLIAAgGQAAgXgBgGQAAgHgDgCIgGgCQgHgCAAgEQAAgDADgCQACgCAFgCIAQgFIAMgCQAFAAACAQIAAADIABAAQAGgKAHgFQAGgGAIABQAIgBAFAGQAFAFAAAJQAAAIgEAFQgEAFgHAAIgGgBIgFgEIgDgFQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAAAgBAAQgIAAgDAMQgDALAAAkQAAALABAGQABAFADABIAGACQAHACAAAFQAAAEgHACQgGACgRAAQgSAAgGgCg");
	this.shape_1.setTransform(161.6,2.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AgnAuQgRgSgBgaQABgcASgSQARgTAbAAQAYAAANAOQAOANABAXQgBAIgCACQgCACgJAAIguAAQgFAAgCgCQgCgCAAgDQAAgDACgCQACgCAEAAIAaAAIAGgBQAAAAAAAAQAAAAABgBQAAAAAAgBQAAAAAAgBQAAgMgIgIQgHgIgLAAQgPAAgHANQgHAMAAASQAAASAKAOQAKAOAOAAQAJAAAGgCQAHgCAFgEIAFgDQAGgFAEAAQAAAAABAAQAAAAABAAQAAAAABABQABAAAAAAQAAABABAAQAAABAAAAQAAABAAABQABAAAAABQAAADgEAEQgCAEgGAEQgKAJgKAEQgKAEgLAAQgZAAgSgSg");
	this.shape_2.setTransform(150.2,2.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AgFBKQgHgCgEgFQgEgEgCgGQgCgHAAgTIAAhAIgLAAIgEgBIgBgDIAAgDQAAgEANgKIAFgFIAFgEQANgMAEAAIADACQABAAAAABQAAAAAAAAQABAAAAABQAAAAAAABIAAAWIAbAAIAEACIABAEIAAADQAAADgBACIgEABIgZAAIgCABIgBADIAAA8QAAAQADADQACAFAHAAQAEAAAGgCIAJgDQAAAAABABQABAAAAAAQABAAAAAAQABABAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAAHgKAGQgLAGgNAAQgHAAgFgBg");
	this.shape_3.setTransform(139.5,1.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AgFBKQgHgCgEgFQgEgEgCgGQgCgHAAgTIAAhAIgLAAIgEgBIgBgDIAAgDQAAgEANgKIAFgFIAFgEQANgMAEAAIADACQABAAAAABQAAAAAAAAQABAAAAABQAAAAAAABIAAAWIAbAAIAEACIABAEIAAADQAAADgBACIgEABIgZAAIgCABIgBADIAAA8QAAAQADADQACAFAHAAQAEAAAGgCIAJgDQAAAAABABQABAAAAAAQABAAAAAAQABABAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAAHgKAGQgLAGgNAAQgHAAgFgBg");
	this.shape_4.setTransform(130.8,1.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AAWA6IgHgHIgFADQgOAKgPAAQgSAAgLgKQgLgLAAgRQAAgTAOgKQAOgLAZAAQAGAAADACQADACAAAEQAAAGgIAAQgMAAgHAGQgHAGAAALQAAAJAGAGQAGAGALAAQALAAAFgFQAFgGAAgMIAAguQAAgLgEgFQgFgGgIAAQgGAAgFACQgFADgFAGIgCADQgIAJgIAAQgFAAgDgDQgDgDAAgFQAAgMAPgIQAOgIAWAAQANAAAJAEQAKAEAFAGQAEAFACAIQABAHAAARIAAAnIABAKQABAEADAAIAEABQAHACAAAFQAAAFgIAFQgIAFgLAAQgFAAgGgGg");
	this.shape_5.setTransform(120.1,2.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AgUBXQgGgBAAgGQAAgEAFgBIAHgEQACgCABgIIAAgXIAAgTIAAgXIAAgJQAAgfgBgJQgBgJgDgBIgHgDQgIgCAAgEQAAgDADgCQACgDAJgDIAQgEIAMgBQADAAACACQABACAAAGIAAAJQgBArAAAsIABApQAAAKACABIAHAEQAGADAAAEQAAAFgGACQgGABgQAAQgSAAgGgCg");
	this.shape_6.setTransform(109.8,0);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("Ag/BWQgGgCgBgFQABgFAHgDIAGgDQACgCABgOIABg0IgBguQAAgSgCgCQgCgCgGgCQgHgDAAgFQAAgEAFgDQADgBAIAAIAMAAIAPAAIAYgBIATAAQAbAAAOALQANALABAYQgBAZgRAOQgQANggAAQgMgBAAgHQAAgJAKABQAPAAAJgJQAKgIAAgSQAAgQgKgJQgKgHgSgBQgJAAgEACQgDABgBADIgCALIAAAaIAAA1IABAjQAAAJACACIAGADQAHACAAAFQAAAFgGACQgHACgUAAQgSAAgIgCg");
	this.shape_7.setTransform(99.6,0.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AgnAuQgRgSAAgaQgBgcATgSQASgTAbAAQAXAAAOAOQANANAAAXQAAAIgCACQgCACgJAAIguAAQgEAAgDgCQgBgCAAgDQAAgDABgCQACgCAFAAIAZAAIAFgBQABAAAAAAQAAAAABgBQAAAAAAgBQAAAAAAgBQAAgMgIgIQgIgIgLAAQgOAAgHANQgHAMAAASQAAASAKAOQAJAOAPAAQAJAAAHgCQAGgCAFgEIAFgDQAGgFAEAAQAAAAABAAQAAAAABAAQAAAAABABQABAAAAAAQAAABABAAQAAABAAAAQAAABAAABQAAAAAAABQAAADgCAEQgEAEgFAEQgKAJgKAEQgKAEgMAAQgYAAgSgSg");
	this.shape_8.setTransform(78.8,2.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AgIA/IgNgCIgEACIgDABIgDAAIgDgCQgEgDgEgKQgDgKAAgJQAAgEACgDQACgCAEAAQAFAAAGAKIAEAHQAEAFAHADQAGACAGAAQAIAAAFgEQAEgEAAgHQABgKgUgKIgHgDQgTgKgHgHQgHgIAAgLQAAgQAMgKQAKgKATAAIAHAAIAJACIAFgCIAEgBQAGAAAGAKQAGAJAAALQAAAEgDADQgBACgDAAQgDAAgDgCQgDgDgDgGQgFgHgFgDQgFgDgHAAQgGAAgEAEQgFAEAAAGQAAAGAFAEQAEAEAOAIIACABQAiAQAAATQAAARgNAMQgNALgUAAg");
	this.shape_9.setTransform(67,2.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("AgnAuQgRgSAAgaQgBgcATgSQASgTAbAAQAXAAAOAOQANANAAAXQAAAIgCACQgCACgJAAIguAAQgEAAgCgCQgCgCAAgDQAAgDACgCQABgCAFAAIAZAAIAFgBQABAAAAAAQAAAAABgBQAAAAAAgBQAAAAAAgBQAAgMgIgIQgIgIgLAAQgOAAgHANQgHAMAAASQAAASAKAOQAJAOAPAAQAJAAAHgCQAGgCAFgEIAFgDQAGgFAEAAQAAAAABAAQAAAAABAAQAAAAABABQABAAAAAAQAAABABAAQAAABAAAAQAAABAAABQAAAAAAABQAAADgCAEQgEAEgFAEQgKAJgKAEQgKAEgMAAQgYAAgSgSg");
	this.shape_10.setTransform(55.4,2.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AgnAuQgRgSAAgaQAAgcASgSQARgTAcAAQAXAAANAOQAPANAAAXQAAAIgDACQgCACgJAAIguAAQgFAAgCgCQgCgCAAgDQAAgDACgCQADgCAEAAIAZAAIAFgBQABAAAAAAQAAAAABgBQAAAAAAgBQAAAAAAgBQAAgMgIgIQgIgIgKAAQgPAAgHANQgHAMAAASQAAASAKAOQAKAOAOAAQAJAAAHgCQAFgCAGgEIAFgDQAGgFAEAAQAAAAABAAQAAAAABAAQAAAAABABQABAAAAAAQAAABABAAQAAABAAAAQAAABAAABQABAAAAABQgBADgDAEQgCAEgGAEQgKAJgKAEQgKAEgLAAQgZAAgSgSg");
	this.shape_11.setTransform(42.6,2.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AARBYQgGgCAAgFQAAgEAGgDIAFgCQACgCACgEIABgSQAAgogFgJQgFgKgNAAQgGAAgGAEQgFAEgEAGQgCAFgBAJIgBAhQAAANABAEQABAEACABIAFACQAGADAAAEQAAAFgGACQgGABgQAAQgTAAgGgCQgGgBAAgGQAAgEAGgCIADgBQAEgCABgFIABgSIAAgUIAAgTIAAg3QgBgNgCgDQgBgCgIgCQgHgBAAgFQAAgDADgCIAOgHIAMgDIAMgBQAEAAABACQACACAAAGIAAAFIgBAxIAAAFIAAAEIACABIADgEIAEgEQAGgHAHgCQAGgDAIAAQAVAAAKANQAKAOAAAbIAAALIAAAVIAAAHQAAAHACACQABADADACIADABQAGACAAAEQAAAGgGABQgGACgTAAQgQAAgGgBg");
	this.shape_12.setTransform(28.7,0);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("AgSBVQgQgGgNgLQgOgNgIgSQgHgSAAgVQAAgRAFgOQAFgPAKgMQAMgPARgHQARgIAUAAIAPABIAXAFIACgBIAKgCIAEACIADADQAEAHADAJQACAJAAAIQAAAFgCACQgBADgFAAQgFAAgJgLIgIgJQgGgHgKgDQgKgEgLAAQgYAAgNAQQgOARAAAcQAAAkASAXQARAXAaAAQAKAAAKgEQAJgDAHgGIAGgHQAFgHAEAAQADAAACADQACADAAAGQAAALgDAHQgEAHgFAAIgBgBIgCAAQgLAGgMADQgLADgMAAQgSAAgQgGg");
	this.shape_13.setTransform(13.4,0.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("AgtBQQgPgKAAgNQAAgGAEgEQACgEAHAAQAFAAAEACQACADACAGQACAJAJAFQAHAFAPAAQAQAAAKgGQALgGAAgKQAAgFgEgDQgEgEgHAAIgPABIgSABQgVAAgNgHQgLgHAAgKQAAgGAEgGQAEgFAKgGQgIgGgDgHQgEgIAAgKQAAgUAPgNQAPgNAXAAIAMABIATAEQAEAAAGgDQAFgCAHgFIAFAEIABAEQAAAFgEAFQgEAFgHADIADAKIACAKQAAAUgPANQgPAMgXAAIgNgBIgLgCIgEAEIgCAFQABAFAFADQAGADAMAAIASgBIATgCQARAAAJAHQAJAHAAANQAAATgTANQgTANgcAAQgYAAgQgJgAgTg8QgHAIAAAMQABANAFAHQAHAIAKAAQAJAAAHgIQAHgHAAgNQAAgMgGgIQgIgIgJAAQgJAAgHAIg");
	this.shape_14.setTransform(-7.8,4.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("AAQA8QgFgBgBgFQAAgEAHgDIAEgCQADgCABgEIABgTQAAgmgFgKQgFgKgNAAQgFAAgGAEQgGAEgDAHQgDAFgBAJIgBAhIABAQQABAEACABIAFACQAGADAAAEQAAAFgFACQgHABgQAAQgSAAgGgCQgHgBABgGQAAgEAFgCIAEgBQADgCABgEIABgOIAAgHIAAgLIAAgLQAAgTgBgHQAAgFgDgCIgGgCQgHgCAAgEQAAgCACgDIAHgEIASgGIANgCQAEAAABACQACABAAAFIAAAIIAAABIABABIAAAAIABgBIACgDIADgCQANgMAPAAQAIAAAIADQAJAEAFAHQAGAHADAJQABAJAAATIAAAQIAAAIIAAAHIABANQACADADACIADABQAGACAAAEQAAAGgGABQgFACgTAAQgRAAgGgCg");
	this.shape_15.setTransform(-22,2.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E47").s().p("AgVBXQgGgCAAgFQAAgFAGgCIADgBQADgCACgEIABgNIAAgIIAAgKIAAgMQAAgUgBgFQgBgFgDgCIgFgCQgIgDAAgEQAAgCACgDIAIgEIASgGIAMgCQAEAAABACQACADAAAFIAAAHIgBAGIgBAeIAAABIAAAeQAAAMABAEQABAGADAAIAEACQAHADAAAEQAAAFgGADQgGABgQAAQgSAAgGgCgAgOg9QgGgEAAgHQAAgGAGgFQAGgFAIAAQAHAAAFAFQAGAEAAAHQAAAGgGAFQgGAFgHAAQgIAAgFgFg");
	this.shape_16.setTransform(-32.7,0.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E47").s().p("AgJA/IgMgCIgEACIgEABIgCAAIgDgCQgEgDgDgKQgEgKAAgJQAAgEADgDQACgCACAAQAGAAAGAKIAFAHQADAFAGADQAHACAGAAQAIAAAFgEQAFgEgBgHQAAgKgTgKIgHgDQgTgKgHgHQgGgIAAgLQgBgQALgKQAMgKARAAIAIAAIAIACIAHgCIADgBQAGAAAGAKQAFAJAAALQAAAEgBADQgCACgEAAQgDAAgCgCQgDgDgEgGQgEgHgFgDQgFgDgGAAQgHAAgEAEQgEAEAAAGQAAAGAEAEQAEAEAPAIIABABQAiAQAAATQAAARgNAMQgNALgUAAg");
	this.shape_17.setTransform(-41.5,2.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#006E47").s().p("AAWA6IgHgHIgFADQgOAKgPAAQgSAAgLgKQgLgLAAgRQAAgTAOgKQAOgLAZAAQAGAAADACQADACAAAEQAAAGgIAAQgMAAgHAGQgHAGAAALQAAAJAGAGQAGAGALAAQALAAAFgFQAFgGAAgMIAAguQAAgLgEgFQgFgGgIAAQgGAAgFACQgFADgFAGIgCADQgIAJgIAAQgFAAgDgDQgDgDAAgFQAAgMAPgIQAOgIAWAAQANAAAJAEQAKAEAFAGQAEAFACAIQABAHAAARIAAAnIABAKQABAEADAAIAEABQAHACAAAFQAAAFgIAFQgIAFgLAAQgFAAgGgGg");
	this.shape_18.setTransform(-53.1,2.8);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#006E47").s().p("AgnAuQgSgSAAgaQABgcARgSQASgTAbAAQAYAAANAOQAOANABAXQgBAIgCACQgCACgJAAIguAAQgEAAgDgCQgCgCAAgDQAAgDACgCQADgCADAAIAZAAIAHgBQAAAAAAAAQAAAAABgBQAAAAAAgBQAAAAAAgBQAAgMgIgIQgHgIgLAAQgPAAgHANQgHAMAAASQAAASAKAOQAKAOAOAAQAJAAAGgCQAHgCAGgEIAEgDQAGgFADAAQABAAABAAQAAAAABAAQAAAAABABQAAAAABAAQAAABABAAQAAABAAAAQAAABAAABQABAAAAABQAAADgEAEQgDAEgEAEQgLAJgKAEQgKAEgLAAQgaAAgRgSg");
	this.shape_19.setTransform(-66.1,2.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#006E47").s().p("AgUBXQgGgBAAgGQAAgEAFgBIAHgEQACgCABgIIAAgXIAAgTIAAgXIAAgJQAAgfgBgJQgBgJgDgBIgHgDQgIgCAAgEQAAgDADgCQACgDAJgDIAQgEIAMgBQADAAACACQABACAAAGIAAAJQgBArAAAsIABApQAAAKACABIAHAEQAGADAAAEQAAAFgGACQgGABgQAAQgSAAgGgCg");
	this.shape_20.setTransform(-76.2,0);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#006E47").s().p("Ag/BWQgGgCAAgFQAAgFAIgDIAEgDQADgCACgOIABg0IgBguQgCgSgBgCQgCgCgGgCQgHgDABgFQAAgEADgDQAEgBAIAAIANAAIANAAIAZgBIATAAQAbAAAOALQANALAAAYQABAZgSAOQgRANggAAQgLgBAAgHQAAgJAKABQAPAAAKgJQAJgIAAgSQAAgQgJgJQgKgHgUgBQgIAAgEACQgEABgBADIgBALIgBAaIAAA1IABAjQABAJACACIAFADQAIACAAAFQAAAFgHACQgGACgUAAQgSAAgIgCg");
	this.shape_21.setTransform(-86.4,0.1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#006E47").s().p("AgXANQgEAAgCgCQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAgBAAAAIABgGIADgGQABgEACgBQACgBAFAAIAGAAIAKAAIAVAAIADgBQAEAAACACQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAABQAAAHgDAFQgEAGgGAAIgGAAIgHAAIgaABIgCAAg");
	this.shape_22.setTransform(-98.2,2.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#006E47").s().p("AAYBYQgBgCgBgEIAAgGIAAgCIgBgBIgDADIgGAEQgGAFgGADQgIACgHAAQgXAAgOgQQgPgQAAgbQAAgeAQgRQARgTAaAAIAJABQADABACADQACACAAAEQAAAGgIAAIgDAAIgDAAQgOAAgHALQgIAKAAATQAAAVAJAMQAIANAOAAQAMAAAHgHQAHgHAAgNIAAgiIAAg3QAAgJgCgDQgCgDgEgCIgDgBQgHgCgBgEQABgEACgCIANgGIANgEIAMgBQADAAACACQACADAAAFIAAAGIgCBLIABAzQACALACACIAIADQAGABAAAFQAAAFgSAGIgMADIgJABQgEAAgBgCg");
	this.shape_23.setTransform(-109.1,0.1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#006E47").s().p("AAHANIgOglQgHgRgGgDIgDgCQgHgCAAgFQAAgFAGgCQAGgCATAAQAQAAAHACQAFACABAFIgCADIgCADIgEACQgFACAAACIACAIIALAaIAKAXQACAFACAAQACAAACgDIAFgLIAOgeQAEgLAAgFIgBgEIgDgDIgDgCQgGgCABgDQgBgFAGgCQAFgCAPAAQANAAAGACQAEACAAAFQAAAEgGADIgEABQgGADgLAaIgCAGIgGAKQgbA/gIAAQgJAAgVgygAhHAHIgDgHIgJgVQgIgUgEgDIgFgCQgGgCgBgFQABgFAFgCQAHgCAUAAQAQAAAGACQAGACAAAFIgBAEIgCACIgEACQgFACAAACIADAKIAJAYIAKAWQADAGACAAQADAAAEgIIAEgIIACgEQABAAAAAAQABAAAAgBQABAAABAAQAAAAABAAQABAAAAAAQABAAABAAQAAABABAAQAAABAAAAQABAAAAABQABAAAAABQAAAAAAABQAAABAAABQAAADgDAHQgNAcgGAJQgFAJgEAAQgJAAgYg4g");
	this.shape_24.setTransform(-126.6,3);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#006E47").s().p("AgrAuQgSgSAAgcQAAgaASgSQASgTAbAAQAbAAARARQAQASAAAaQAAAcgSATQgSATgaAAQgaAAgRgSgAgXgkQgHAKAAARQAAAXALAQQAJARAOAAQAMAAAIgLQAIgKgBgQQAAgXgKgQQgLgRgNAAQgMAAgIAKg");
	this.shape_25.setTransform(-143.7,2.8);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#006E47").s().p("AgkA8QgGgBAAgGQAAgEAGgCIADgBQADgCABgEQACgEAAgKIgBgHIAAgLIAAgGQAAgXgBgGQgBgHgCgCIgGgCQgHgCAAgEQAAgDADgCQABgCAGgCIAQgFIALgCQAGAAACAQIAAADIAAAAQAHgKAHgFQAHgGAGABQAJgBAFAGQAFAFAAAJQAAAIgEAFQgEAFgGAAIgHgBIgFgEIgDgFQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAAAgBAAQgIAAgDAMQgDALAAAkQAAALABAGQACAFACABIAGACQAHACAAAFQAAAEgHACQgGACgRAAQgSAAgGgCg");
	this.shape_26.setTransform(-154.9,2.7);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#006E47").s().p("AgSBVQgQgGgNgLQgOgNgIgSQgHgSAAgVQAAgRAFgOQAFgPAKgMQAMgPARgHQARgIAUAAIAOABIAYAFIACgBIAKgCIAEACIADADQAEAHADAJQADAJgBAIQAAAFgCACQgBADgFAAQgFAAgJgLIgHgJQgHgHgKgDQgKgEgLAAQgYAAgNAQQgOARAAAcQAAAkASAXQARAXAaAAQAKAAAKgEQAJgDAHgGIAFgHQAGgHAEAAQADAAACADQACADAAAGQAAALgDAHQgDAHgGAAIgBgBIgCAAQgLAGgMADQgLADgNAAQgRAAgQgGg");
	this.shape_27.setTransform(-168.1,0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.crowdplease, new cjs.Rectangle(-178.6,-16.5,357.3,33), null);


(lib.bottomleftnineten = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.nineteenbottomleft();
	this.instance.parent = this;
	this.instance.setTransform(-58.5,-20.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bottomleftnineten, new cjs.Rectangle(-58.5,-20.5,117,41), null);


(lib.blackwideskyscraper = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgRBA2FMAAAhsJMAiDAAAMAAABsJg");
	this.shape.setTransform(0,0,0.753,0.867);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.blackwideskyscraper, new cjs.Rectangle(-82.1,-300,164.3,600.1), null);


(lib.fourteenctarollover = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_1 = function() {
		this.stop();
	}
	this.frame_11 = function() {
		this.stop();
	}
	this.frame_23 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(1).call(this.frame_1).wait(10).call(this.frame_11).wait(12).call(this.frame_23).wait(7));

	// Layer_1
	this.instance = new lib.ctarectanglevideo();
	this.instance.parent = this;
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({alpha:1},9).wait(2).to({alpha:0},10).wait(8));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-63,-15.5,126.1,31.1);


// stage content:
(lib.leaderboardnineteen = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_49 = function() {
		//onhover event to reveal green cta rectangle over orange rectangle
		this.btn_main.addEventListener("mouseover", fl_MouseOverHandler.bind(this));
		this.btn_main.addEventListener("mouseout", fl_MouseOutHandler.bind(this));
		
		function fl_MouseOverHandler()
		{
			this.cta_rollover.gotoAndPlay(2);
		}
		
		function fl_MouseOutHandler()
		{
		this.cta_rollover.gotoAndPlay(13);
		}
	}
	this.frame_243 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(49).call(this.frame_49).wait(194).call(this.frame_243).wait(3));

	// button
	this.btn_main = new lib.mainbutton();
	this.btn_main.parent = this;
	this.btn_main.setTransform(365.8,47.1,3.544,0.143,0,0,0,0.3,0.7);
	new cjs.ButtonHelper(this.btn_main, 0, 1, 2, false, new lib.mainbutton(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn_main).wait(246));

	// grey-rectangle
	this.instance = new lib.greyrectangle();
	this.instance.parent = this;
	this.instance.setTransform(364,45);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(246));

	// fade-from-black
	this.instance_1 = new lib.blackwideskyscraper();
	this.instance_1.parent = this;
	this.instance_1.setTransform(366.7,50.5,4.456,0.171,0,0,0,0.6,0.6);
	this.instance_1.filters = [new cjs.ColorFilter(0, 0, 0, 1, 255, 255, 255, 0)];
	this.instance_1.cache(-84,-302,168,604);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({regX:0.2,regY:0.7,scaleY:0.16,x:364.9,y:47,alpha:0},9).wait(237));

	// kale-logo
	this.instance_2 = new lib.kalelogo();
	this.instance_2.parent = this;
	this.instance_2.setTransform(652.6,44.5);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({scaleX:0.09,scaleY:0.09},0).to({scaleX:1.13,scaleY:1.13,alpha:1},6,cjs.Ease.get(1)).to({scaleX:1,scaleY:1},7,cjs.Ease.get(1)).wait(224));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EgidASmMAAAglLMBIDAAAMAAAAlLg");
	mask.setTransform(240.6,53);

	// get-party-started
	this.instance_3 = new lib.getpartystartednineteen();
	this.instance_3.parent = this;
	this.instance_3.setTransform(104,13.6);
	this.instance_3.alpha = 0;

	var maskedShapeInstanceList = [this.instance_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(205).to({x:-246},0).to({x:114,alpha:1},10,cjs.Ease.get(1)).to({x:104},8,cjs.Ease.get(1)).wait(23));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("EgidASmMAAAglLMBIDAAAMAAAAlLg");
	mask_1.setTransform(240.6,53);

	// holiday-platters-small-bites
	this.instance_4 = new lib.holidayplatterssmall();
	this.instance_4.parent = this;
	this.instance_4.setTransform(192,32.7);
	this.instance_4.alpha = 0;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(205).to({x:-158},0).to({x:202,alpha:1},10,cjs.Ease.get(1)).to({x:192},8,cjs.Ease.get(1)).wait(23));

	// ready-to-serve-shrimp
	this.instance_5 = new lib.readytoserveshrimp();
	this.instance_5.parent = this;
	this.instance_5.setTransform(151.7,25.4);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(145).to({alpha:1},10).wait(40).to({alpha:0},5).wait(46));

	// party-perfect
	this.instance_6 = new lib.partyperft();
	this.instance_6.parent = this;
	this.instance_6.setTransform(176.5,25.4);
	this.instance_6.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(95).to({alpha:1},10).wait(40).to({alpha:0},5).wait(96));

	// crowd-pleasing-cheese
	this.instance_7 = new lib.crowdplease();
	this.instance_7.parent = this;
	this.instance_7.setTransform(198.7,25.4);
	this.instance_7.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(37).to({x:-148.1},0).to({x:208.7,alpha:1},10,cjs.Ease.get(1)).to({x:198.7},8,cjs.Ease.get(1)).wait(40).to({alpha:0},5).wait(146));

	// mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	mask_2.graphics.p("EggvASmMAAAglLMBGVAAAMAAAAlLg");
	mask_2.setTransform(240.6,53);

	// shop-now
	this.instance_8 = new lib.getinspired();
	this.instance_8.parent = this;
	this.instance_8.setTransform(82.9,65.2);
	this.instance_8.alpha = 0;

	var maskedShapeInstanceList = [this.instance_8];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(49).to({x:-58.1},0).to({x:87.9,alpha:1},10,cjs.Ease.get(1)).to({x:82.9},8,cjs.Ease.get(1)).wait(179));

	// mask (mask)
	var mask_3 = new cjs.Shape();
	mask_3._off = true;
	mask_3.graphics.p("EgidASmMAAAglLMBIDAAAMAAAAlLg");
	mask_3.setTransform(240.6,53);

	// cta-rollover
	this.cta_rollover = new lib.fourteenctarollover();
	this.cta_rollover.parent = this;
	this.cta_rollover.setTransform(83,66.3);
	this.cta_rollover.alpha = 0;

	var maskedShapeInstanceList = [this.cta_rollover];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_3;
	}

	this.timeline.addTween(cjs.Tween.get(this.cta_rollover).wait(49).to({x:-57},0).to({x:88,alpha:1},10,cjs.Ease.get(1)).to({x:83},8,cjs.Ease.get(1)).wait(179));

	// mask (mask)
	var mask_4 = new cjs.Shape();
	mask_4._off = true;
	mask_4.graphics.p("EgidASmMAAAglLMBIDAAAMAAAAlLg");
	mask_4.setTransform(240.6,53);

	// cta-rectangle
	this.instance_9 = new lib.ctarectangle();
	this.instance_9.parent = this;
	this.instance_9.setTransform(83,66.3);
	this.instance_9.alpha = 0;

	var maskedShapeInstanceList = [this.instance_9];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_4;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(49).to({x:-57},0).to({x:88,alpha:1},10,cjs.Ease.get(1)).to({x:83},8,cjs.Ease.get(1)).wait(179));

	// bottom-right
	this.instance_10 = new lib.nineteenright();
	this.instance_10.parent = this;
	this.instance_10.setTransform(553,45);
	this.instance_10.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(26).to({alpha:1},10).wait(210));

	// top-right
	this.instance_11 = new lib.topright();
	this.instance_11.parent = this;
	this.instance_11.setTransform(442.5,26.5);
	this.instance_11.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(21).to({alpha:1},10).wait(215));

	// bottom-left
	this.instance_12 = new lib.bottomleftnineten();
	this.instance_12.parent = this;
	this.instance_12.setTransform(346.5,69.5);
	this.instance_12.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(16).to({alpha:1},10).wait(220));

	// table
	this.instance_13 = new lib.nineteentable_1();
	this.instance_13.parent = this;
	this.instance_13.setTransform(364,45);

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(246));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(362.2,32.1,731.8,114.8);
// library properties:
lib.properties = {
	id: '85088BD5353243C8B4895C262600CED3',
	width: 728,
	height: 90,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/index_atlas_.png", id:"index_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['85088BD5353243C8B4895C262600CED3'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;